### ISSUE TITLE
How is this SDK made?

### ISSUE THREAD

**Issue by ranman** [aws/aws-iot-device-sdk-python#1]
1) Thanks for throwing this up on github, you guys rock.
2) It's not a big deal but is this SDK auto-generated? If so do you have a "contrib" guide / policy?
3) Do we have a testing suite?

There's a lot of non-idiomatic python in here and before I go willy-nilly trying to fix a bunch of stuff I wanted to understand how this was developed so we don't waste our time. I'm not a python zealot on whitespace and CamelCasing or anything like that but I do enjoy making things work well and fast.

**Comment by liuszeng** [comment]
Hi @ranman ,

Thank you very much for your interest in AWS IoT Python SDK!

The AWS IoT Python SDK is not auto-generated. You can submit pull request through this Github repository if you have any inputs on the SDK implementation details. Our process of taking Github pull request is to merge it into our development branch and go through our internal tests for verification. Changes will be incorporated into future releases.

We are always willing to see developers providing sparkling thoughts and inputs to the SDK and contributing back. This is indeed how the SDK evolves and becomes better.

Please feel free to call out if you have more questions.

Thanks,
Liusu
