### ISSUE TITLE
How to connect Raspberry pi to $aws/things/thingName/shadow/update/accepted

### ISSUE THREAD

**Issue by HareshArunachalam** [aws/aws-iot-device-sdk-python#100]
I am able to connect my Raspberry pi device with the  $aws/things/thingName/shadow/update/delta using the basic shadow Delta listener program given in the samples. Can you help me out in subscribing with the update/accepted topic ?

Thanks

**Comment by liuszeng** [comment]
Hi @HareshArunachalam ,

Thank you very much for using AWS IoT Device SDK for Python.

Subscribing to shadow update/accepted and update/rejected topics are automatically handled by the SDK when you call API `deviceShadow.shadowUpdate(...)`. For more details, please refer to the API documentation:
https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html#AWSIoTPythonSDK.core.shadow.deviceShadow.deviceShadow.shadowUpdate

Hope the above helps. Please feel free to reopen this issue if you have further questions.

Thanks,
Liusu

**Comment by HareshArunachalam** [comment]
Hi @liuszeng 

In my case, I am updating the Thing shadow via the AWS Lambda function and I want to read the update/accepted topic and don't want to update anything from my Raspberry pi device. I want Raspberry pi to only listen to the Thing shadow state, which I had already done using Delta, but the issue with delta is that it only persist values that are different between the desired and reported property, I want to have everything that is updated in the desired property, that case update/accepted is ideal. 
Is there way to only listen to update/accepted topic? 

Thanks,
Haresh

**Comment by liuszeng** [comment]
Hi @HareshArunachalam ,

Thank you very much for clarifying the use case here.

Currently, subscription to shadow update accepted topic is bundled with the shadow APIs provided by the SDK shadow client. To only subscribe to a single shadow response topic, you can directly use the plain MQTT client to do the subscription ([API doc](https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html#AWSIoTPythonSDK.MQTTLib.AWSIoTMQTTClient.subscribe)):
```
client.subscribe("$aws/things/<THING_NAME>/shadow/update/accepted", 0, YourCallback)
```

For more information about shadow topics, you can take a look at the following documentation:
https://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-mqtt.html

Thanks,
Liusu

**Comment by HareshArunachalam** [comment]
Hi @liuszeng 

Thanks for the quick response and it helped me solve my issue, I am now able to subscribe to update/accepted .

Regards,
Haresh
