### ISSUE TITLE
subscribe returns true, but customcallback parameter is not called

### ISSUE THREAD

**Issue by GIovanniMoya** [aws/aws-iot-device-sdk-python#105]
Hello,

I am making a system that publishes sensor data from a Raspberry Pi to AWS and from AWS back to the Raspberry Pi.  AWS IoT has a trigger to store this message in dynamoDB and then invoke a lambda function to publish to a topic subscribed by the RaspberryPi.  After the publish is invoked by the lambda function, the RapsberryPi subscribe function returns true, but the customCallback is not called.  I verified the lambda function is correctly publishing the message to the topic through AWS IoT test subscribe feature.  Please advise.

RaspberryPi side code:

```
from time import sleep
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient

myMQTTClient = AWSIoTMQTTClient("XXXXXXX")
# this is the unique thing endpoint with the .503 certificate
myMQTTClient.configureEndpoint("XXXXXXXXXXX.iot.us-west-2.amazonaws.com", 8883)
# credentials
myMQTTClient.configureCredentials(
   "aws-iot-device-sdk-python/deviceSDK/certs/VeriSign-Class3-Public-Primary-Certification-Authority-G5.pem.txt",
   "aws-iot-device-sdk-python/deviceSDK/certs/XXXXXXXXXX-private.pem.key",
   "aws-iot-device-sdk-python/deviceSDK/certs/XXXXXXXXXX-certificate.pem.crt")
# above has the path for the CA root cert, private key cert, and device cert
myMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
myMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
myMQTTClient.configureMQTTOperationTimeout(20)  # 20 sec

# callback function for AWS sub
def on_subscribe(client, userdata, message):
   msg = None
   while msg is None:
       msg = message.payload
       print(msg)
       sleep(2)
   return message.payload

# register callback
myMQTTClient.onMessage = on_subscribe

# connect and subscribe
myMQTTClient.connect()

try:
   myMQTTClient.subscribe('thing02/water', 1, on_subscribe)
except KeyboardInterrupt:
   print('exited')
```

AWS lambda side code:

```
import json
import boto3

def lambda_handler(event, context):
   #testing for pi publishing
   message = {
       'topic': 'thing02/water',
       'payload': {'message': 'test'}
   }

   boto3.client(
       'iot-data',
       region_name='us-west-2',
       aws_access_key_id='<access-key>',
       aws_secret_access_key='<secret-access-key'
       ).publish(
           topic='thing02/water',
           payload=json.dumps(message),
           qos=1
           )
   print(json.dumps(message))
```

**Comment by liuszeng** [comment]
Hi @GIovanniMoya ,

Thank you very much for your interest in AWS IoT Device SDK for Python.

There are several things that look suspicious here:
1. In your Raspberry Pi code, the program seems to exit immediately after your subscribe call finishes. Note that AWS IoT features a long live MQTT connection. To keep that active, you will need to keep your main thread alive. If you are not interested in publishing messages, you can simply put a loop at the end.
2. In your callback configuration, I see that you have configured 2 callbacks, one for the general message arrival callback and the other one for per subscription message callback. Having two of them might be redundant in this case. You might also want to watch for the callback function signature as they are different. See more details here:
Per subscription message callback: https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html#AWSIoTPythonSDK.MQTTLib.AWSIoTMQTTClient.subscribe
General message arrival callback: https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html#AWSIoTPythonSDK.MQTTLib.AWSIoTMQTTClient.onMessage
3. You may want to check the `while` statement in `on_subscribe` callback.

Hope the above helps.

Thanks,
Liusu

**Comment by GIovanniMoya** [comment]
Hi Liusu,

Thank you for the prompt answer and detailed advice.  I figured out the problem is the sleep(2).  It must have prevented the code from accessing the server response.

Thank you for the help! Everything is working now.
