### ISSUE TITLE
Publish and Subscribe multiple topics Question? 

### ISSUE THREAD

**Issue by boppana113** [aws/aws-iot-device-sdk-python#107]
I am using a raspberrypi as my thing. I successfully got the basicPubSub.py file to connect to my AWS IoT console for both publishing/subscribing. However, it seems that the example can only subscribe/publish to one topic. Is there any way in the example code to publish/subscribe to multiple topics at once? 

Thanks.

**Comment by liuszeng** [comment]
Hi @boppana113 ,

Thank you very much for your interest in AWS IoT Device SDK for Python.

Currently, there is no API allowing you to subscribe to multiple topics in a same call. You can achieve that by:
1. Perform per topic subscribe in a loop.
2. Use a topic filter wildcard ([AWS IoT doc](https://docs.aws.amazon.com/iot/latest/developerguide/topics.html))

As for publishing to multiple topics, it is restricted by MQTT spec that publish request can only happen to a specific topic, not a topic filter. See more details [here](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718037). Although you can still achieve that by creating some AWS IoT rules that listen on the single topic your application publishes and publish to different topics for you. You can check out the following AWS IoT doc:
https://docs.aws.amazon.com/iot/latest/developerguide/republish-rule.html

Please feel free to reopen the issue or create a new thread if you have more questions.

Thanks,
Liusu
