### ISSUE TITLE
read messages by api

### ISSUE THREAD

**Issue by weblanss** [aws/aws-iot-device-sdk-python#111]
hi , i had connected to my aws account and made some connection . Also i can publish and subscribe  from my another web server .
Now  i am struggling  to read all the data wich was sent to my account . i want to listen all data wich was sent to my account . but lambda_handler  did not  show anything  . How to read data properly ?:
```
import ssl
print(ssl.OPENSSL_VERSION)
import traceback

import logging
import time
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTShadowClient
MQTTv3_1 = 3
MQTTv3_1_1 = 4

DROP_OLDEST = 0
DROP_NEWEST = 1


#KEY_PATH = ''

host = "***2.amazonaws.com"
rootCAPath ='/rootCA.pem'
certificatePath = "***.pem.crt"
privateKeyPath ='***.private.pem.key'
clientId = "est"
topic = "test"

logger = logging.getLogger("AWSIoTPythonSDK.core")
logger.setLevel(logging.DEBUG)
streamHandler = logging.StreamHandler()
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
streamHandler.setFormatter(formatter)
logger.addHandler(streamHandler)

myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId)
myAWSIoTMQTTClient.configureEndpoint(host, 8883)
myAWSIoTMQTTClient.configureCredentials(rootCAPath, privateKeyPath, certificatePath)

myAWSIoTMQTTClient.configureAutoReconnectBackoffTime(1, 32, 20)
myAWSIoTMQTTClient.configureOfflinePublishQueueing(-1) # Infinite offline publishing queueingr
myAWSIoTMQTTClient.configureDrainingFrequency(2) # 2 Hz
myAWSIoTMQTTClient.configureConnectDisconnectTimeout(10) # 10 sec
myAWSIoTMQTTClient.configureMQTTOperationTimeout(5) # % sec

# Connect
myAWSIoTMQTTClient.connect()
time.sleep(2)

# publish
myAWSIoTMQTTClient.publish(topic, "{\"message\": \"my message\"}", 0)
myAWSIoTMQTTClient.publish(topic, "{\"test\": \"test\"}", 0)

print(11111)
def customCallback(client, userdata, message):
    print("Received a new message: ")
    print(message.payload)
    print("from topic: ")
    print(message.topic)
    print("--------------\n\n")


myAWSIoTMQTTClient.subscribe("thing02/test2", 0, customCallback)

```

**Comment by liuszeng** [comment]
Hi @weblanss ,

Can you elaborate more on what you are trying to achieve here? Are you trying to use the SDK and perform subscribe inside your lambda function? Are you trying to receive all messages that are published within your account?

Thanks,
Liusu

**Comment by weblanss** [comment]
i am trying o receive all messages that are published within my account

**Comment by liuszeng** [comment]
Hi @weblanss ,

To receive all messages that are published within the account, you can use wildcard topic filter subscription. You can simply perform subscribe like this:
```
client.subscribe("#", 1, callback)
```

According to MQTT spec, subscribing to topic filter "#" will match with any topics. AWS IoT server will then forward any message published to any topic within your account to that client. For more details, you can take a look at the following documentation:
https://docs.aws.amazon.com/iot/latest/developerguide/topics.html

Thanks,
Liusu

**Comment by weblanss** [comment]
i already tried this :
[myAWSIoTMQTTClient.publish(topic, "{\"message\": \"my message\"}", 0)
myAWSIoTMQTTClient.publish(topic, "{\"test\": \"test\"}", 0)


def customCallback(client, userdata, message):
    print("Received a new message: ")
    print(message.payload)
    print("from topic: ")
    print(message.topic)
    print("--------------\n\n")



myAWSIoTMQTTClient.publish(topic, "{\"test\": \"test\"}", 0)
while True :
    myAWSIoTMQTTClient.subscribe("#", 1, customCallback)
    time.sleep(4)](url)

it's not print any updates

**Comment by weblanss** [comment]
thank , i solved it
