### ISSUE TITLE
Know when the internet is off and on 

### ISSUE THREAD

**Issue by TejaswiniiB** [aws/aws-iot-device-sdk-python#117]
Hi, what I understood from the docs is that, I can use onOffline(), onOnline() callbacks to get a kind of notifications when device's connection to internet is off and on respectively. But it's not working that way, those callbacks aren't getting called. Am I correct? If not what are ways to be notified when internet is off?

Thankyou !!

**Comment by hedeshianaws** [comment]
Thank you for trying the AWS IoT Python Device SDK. The two callbacks you mention, onOnline and onOffline are invoked whenever the MQTT client connects or disconnects (respectively) from the AWS IoT gateway. The callbacks must be set before invoking connect() for the first time. These callbacks are particularly useful when using the auto-reconnect feature letting the SDK automatically manage the connection in the background. 

It is important to remember that these callbacks are tied to whether or not the MQTT client thinks the connection is alive, as the SDK has no concept of "internet is off". Depending on how the internet is "turned off", you may need to wait for a session timeout or force the SDK to try to send something for the TCP operation to error out.

**Comment by TejaswiniiB** [comment]
Okay, thankyou !!
