### ISSUE TITLE
I've finished configuring AWS IOT, but I use it in the /sample/basicPubSub_APICallInCallback.py

### ISSUE THREAD

**Issue by poisonousfish** [aws/aws-iot-device-sdk-python#120]
This is always a problem. I'm using the EC2 server.Can someone help me?
![image](https://user-images.githubusercontent.com/24249565/37874354-fd72a49e-305f-11e8-932d-64a9b9517194.png)

**Comment by poisonousfish** [comment]
The method I use
![image](https://user-images.githubusercontent.com/24249565/37874416-636dfee6-3061-11e8-8e19-964abbbac46a.png)

**Comment by poisonousfish** [comment]
It seemed that I had solved my problem. I used start.sh in the configuration device, but I didn't know I was wrong there before.

**Comment by vareddy** [comment]
Hi @poisonousfish ,
Thank you for your interest in the AWS IoT SDK!
If this issue has been solved, please close this issue. If you find any other problems please open a new issue as it is easier for us to track. 
Thanks!
Varun

**Comment by jackylee1** [comment]
i have the same problem
