### ISSUE TITLE
Getting stuck on TLS? 

### ISSUE THREAD

**Issue by dmateos** [aws/aws-iot-device-sdk-python#121]
Hi, 

I have this running on many devices, a few are consistently getting stuck with this log: 

AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Paho MQTT Client init.
AWSIoTPythonSDK.core.protocol.mqttCore - INFO - ClientID: 5c11417598fb44bd9686c082852c3577
AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Protocol: MQTTv3.1.1
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Register Paho MQTT Client callbacks.
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - mqttCore init.
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: queueSize = 0
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: dropBehavior = Drop Newest
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for draining interval: 0.1 sec
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load CAFile from: /home/emetric/root-ca.cert
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load Key from: /home/emetric/private.key
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load Cert from: /home/emetric/public.key
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: baseReconnectTime = 1 sec
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: maximumReconnectTime = 250 sec
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: minimumConnectTime = 20 sec
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Set maximum connect/disconnect timeout to be 250 second.
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Set maximum MQTT operation timeout to be 5 second
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: queueSize = -1
AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: dropBehavior = Drop Newest
AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Connection type: TLSv1.2 Mutual Authentication

I have seen this before when the clientid doesn't match what is expected, but i can confirm this is correct. 

It just sits there after that and does nothing 

Any insight?

**Comment by liuszeng** [comment]
Hi @dmateos ,

This could happen due to many reasons. Can you verify the following things?
1. Endpoint and port should be correctly configured
    Your endpoint should look like the following:
    ```
    <prefix>.iot.<region>.amazonaws.com
    ```
    If you are using X.509 certificate mutual auth., you should use port 8883. If you are using MQTT over WebSocket, you should use port 443. Currently, Python SDK does not natively support ALPN (MQTT with X.509 certificate through 443).
1. Client ids for different connections should be different.
    AWS IoT does not allow duplicated client ids within the same account in the same region. A new client with used client ids will interfere with previous connections.
1. A TCP/TLS connection can be established to AWS IoT endpoint.
    1. Use the following instructions to check if the TCP connection to AWS IoT is blocked:
        From your <PC> machine try a simple telnet command to the service hostname and port
        ```
        host$> telnet <prefix>.iot.<region>.amazonaws.com 8883
        Trying 54.236.141.103...
        Connected to <endpoint>.
        Escape character is '^]'.

        Connection closed by foreign host.
        host$> 
        ```
        The above shows a successful TCP connection, with the connection eventually being closed due to failed authentication. This would indicate connections on port 8883 are not being blocked. Below shows the same command when attempting on a blocked port:
        ```
        host$> telnet <prefix>.iot.<region>.amazonaws.com 8883
        Trying 54.236.141.103...
        telnet: connect to address 54.236.141.103: Connection refused
        ```
    1. Use the following instructions to check if the TLS connection to AWS IoT can be established:
        Type the following command into the linux command line if you have OpenSSL installed
        ```
        openssl s_client -connect <prefix>.iot.<region>.amazonaws.com:8883 -tls1_2 -CAfile <path to Root CA cert> -cert <Path to device cert> -key <Path to device private key>
        ```
        If the command fails you will get an output similar to below
        ```
        SSL routines:ssl3_write_bytes:ssl handshake failure
        ```
        If it succeeds you will have a success mesage and the command will wait for further input. 

You mentioned that you have seen this before when **client id does not match what is expected**. Can you elaborate more on that? In the meantime, did you see any error logs from the SDK eventually? Can you enable AWS IoT Cloudwatch log and see if there is any service side event getting emitted?

Thanks,
Liusu

**Comment by dmateos** [comment]
Have done some debugging, it is not a library issue sorry. 

Turns out some hosts are picking up ipv6 nameservers from their routers and the amazon endpoint then does not resolve.

**Comment by liuszeng** [comment]
Hi @dmateos ,

Glad to know it works out for you. Closing the issue.

Thanks,
Liusu

**Comment by dmateos** [comment]
Do you guys have any suggestions for how to get past this? Besides stopping the hosts broken ipv6 configuration. 

I think its since AWS have added AAAA records, if their router configuration is broken this happens. 

Sometimes removing the ipv6 resolver from their resolv.conf works, sometimes it doesnt as their router is trying to resolve this too so only 8.8.8.8 works. 

I also cant resolve it elsewhere and supply the IP addr because then i get a SSL error with host mismatch.
