### ISSUE TITLE
Support for MQTT on port 443 using certificates

### ISSUE THREAD

**Issue by vmanikes** [aws/aws-iot-device-sdk-python#127]
Hello Does this library has support for MQTT on port 443 using certificates. I do not see anything in the documentation of it and after a bit of googling I found a [link](https://aws.amazon.com/blogs/iot/how-to-implement-mqtt-with-tls-client-authentication-on-port-443-from-client-devices-python/) how to connect but it is written using Paho. Then what is the point of this library when you are using Paho to do MQTT over 443? Kindly suggest/comment

**Comment by hedeshianaws** [comment]
Hello, thank you for using the AWS IoT Python SDK. I believe what you are looking for is MQTT over Websockets (port 443) using x.509 certificates. This SDK **does** support this mode of operation. There is sample usage in the basic pub/sub sample: https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/basicPubSub/basicPubSub.py#L81

`
# Init AWSIoTMQTTClient
myAWSIoTMQTTClient = None
if useWebsocket:
    myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId, useWebsocket=True)
    myAWSIoTMQTTClient.configureEndpoint(host, 443)
    myAWSIoTMQTTClient.configureCredentials(rootCAPath)
else:
    myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId)
    myAWSIoTMQTTClient.configureEndpoint(host, 8883)
myAWSIoTMQTTClient.configureCredentials(rootCAPath, privateKeyPath, certificatePath)
`

**Comment by vmanikes** [comment]
Thanks man, It is fixed now
