### ISSUE TITLE
Listeners instead of infinite while loop

### ISSUE THREAD

**Issue by vmanikes** [aws/aws-iot-device-sdk-python#130]
Hello all, 
I want to subscribe to a topic until I get a message but I do not want to use an infinite while loop as it is a blocking operation in my use case. I used `subscribe()` and `subscribeAsync()` but I think both are doing the same. Can someone tell me the difference between the two and how to avoid infinite while loop while doing subscribe?

**Comment by liuszeng** [comment]
Hi @vmanikes ,

Can you elaborate more on your user story on "subscribe to a topic until I get a message" and what you mean by "avoid infinite loop while doing subscribe"?

If you would like to subscribe to a topic upon a message arrival, you can achieve that by calling `subscribeAsync(...)` inside your message callback. The major difference between `subscribe(...)` and `subscribeAsync(...)` is that `subscribe(...)` blocks until a `SUBACK` is received while `subscribeAsync(...)` returns immediately and accepts a suback callback to be invoked when `SUBACK` is received.

Thanks,
Liusu

**Comment by vmanikes** [comment]
Hi @liuszeng 
Thanks for your reply, [#24](https://github.com/aws/aws-iot-device-sdk-python/issues/24) helped me figure out things
