### ISSUE TITLE
Certificates over port 443

### ISSUE THREAD

**Issue by martysweet** [aws/aws-iot-device-sdk-python#131]
Hi,

In Feburary, x.509 cert over 443 was announced, allowing better use of AWS IOT behind strict firewalls.

https://aws.amazon.com/about-aws/whats-new/2018/02/aws-iot-core-now-supports-mqtt-connections-with-certificate-based-client-authentication-on-port-443/

![image](https://user-images.githubusercontent.com/20517404/40722384-12feb0b8-6414-11e8-8d3c-312de5106671.png)

https://aws.amazon.com/blogs/iot/mqtt-with-tls-client-authentication-on-port-443-why-it-is-useful-and-how-it-works/

From the looks of the release blog, a parameter (ProtocolNameList) has to be set on the outgoing connection, however, I can't see any trace of this in the source code.

Additionally, when using the following code:
```python
myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId)
myAWSIoTMQTTClient.configureEndpoint(host, 443)
myAWSIoTMQTTClient.configureCredentials(rootCAPath, privateKeyPath, certificatePath)
```
The client sends packets to the broker (observed in WireShark), then times out (presumably because Auth is failing in a weird way).

and using:
```python
myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId, useWebsocket=True)
myAWSIoTMQTTClient.configureEndpoint(host, 443)
myAWSIoTMQTTClient.configureCredentials(rootCAPath, privateKeyPath, certificatePath)
```
Throws an IAM failure, as expected from the way authentication is implemented.

Does this library currently support this feature? or is it only available on FreeRTOS? and certificates over 443 is not supported, will it eventually be supported for this SDK?

Thanks!

**Comment by liuszeng** [comment]
Hi @martysweet,

Unfortunately, X.509 certificate mutual authentication via port 443 is currently not supported by Python SDK. We already have an internal tracker and are actively working on it. As a work-around for now, you can use the following patch to enable this feature:
```
--- a/AWSIoTPythonSDK/core/protocol/paho/client.py
+++ b/AWSIoTPythonSDK/core/protocol/paho/client.py
@@ -787,15 +787,26 @@ class Client(object):
                 self._ssl = SecuredWebSocketCore(rawSSL, self._host, self._port, self._AWSAccessKeyIDCustomConfig, self._AWSSecretAccessKeyCustomConfig, self._AWSSessionTokenCustomConfig)  # Overeride the _ssl socket
                 # self._ssl.enableDebug()
             else:
-                self._ssl = ssl.wrap_socket(
-                    sock,
-                    certfile=self._tls_certfile,
-                    keyfile=self._tls_keyfile,
-                    ca_certs=self._tls_ca_certs,
-                    cert_reqs=self._tls_cert_reqs,
-                    ssl_version=self._tls_version,
-                    ciphers=self._tls_ciphers)
-
+                if self._port == 8883:
+                    self._ssl = ssl.wrap_socket(
+                        sock,
+                        certfile=self._tls_certfile,
+                        keyfile=self._tls_keyfile,
+                        ca_certs=self._tls_ca_certs,
+                        cert_reqs=self._tls_cert_reqs,
+                        ssl_version=self._tls_version,
+                        ciphers=self._tls_ciphers)
+                else:
+                    context = ssl.SSLContext(self._tls_version)
+                    context.load_cert_chain(self._tls_certfile, self._tls_keyfile)
+                    context.verify_mode = self._tls_cert_reqs
+                    context.load_verify_locations(self._tls_ca_certs)
+                    context.set_alpn_protocols(["x-amzn-mqtt-ca"])
+                
+                    self._ssl = context.wrap_socket(sock, server_hostname=self._host, do_handshake_on_connect=False)
+                    
+                    self._ssl.do_handshake()
+                
                 if self._tls_insecure is False:
                     if sys.version_info[0] < 3 or (sys.version_info[0] == 3 and sys.version_info[1] < 5):  # No IP host match before 3.5.x
                         self._tls_match_hostname()
```

Note that the above implementation requires Python support for SSLContext and ALPN, which is only available for Python 2.7.10+ and 3.5+.

Please stay tuned for future releases.

Thanks,
Liusu
