### ISSUE TITLE
Subscribed topics are not getting data after internet restart?

### ISSUE THREAD

**Issue by jay7583** [aws/aws-iot-device-sdk-python#132]
Hi,

I am using AWS Iot python sdk in raspberry pi,it's working fine when i put on bootup and running in shell.

But if program is running and only internet(router) restarts,at that time pi is accessing internet and program is running but it's not receiving published messeges from cloud.it's not giving any error also.

What i'm thinking is mqtt subscripition link is breaking when router is restarting .

Is there any way in AWS IoT python sdk to subscribe again automatically?

**Comment by liuszeng** [comment]
Hi @jay7583,

The SDK does automatic reconnect and resubscribe by default. Note that the offline detection is based on MQTT PINGREQ/PINGRESP, the shorter your keep-alive configuration is, the faster the SDK will be able to detect an offline situation. Once the SDK detects that the client is offline, it starts the reconnect/resubscribe logic.

Can you decrease the keep-alive interval and try again? Connect API documentation can be found here:
https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html#AWSIoTPythonSDK.MQTTLib.AWSIoTMQTTClient.connect

Thanks,
Liusu

**Comment by jay7583** [comment]
Hi @liuszeng 

Thanks for the help.It's working fine.
