### ISSUE TITLE
Creating different iot-devices for different cognito users and downloading certificates to publish,subsribe topics

### ISSUE THREAD

**Issue by jay7583** [aws/aws-iot-device-sdk-python#134]
Hi,
I have implemented cognito userpool,federated pool to give iot access to users.Now i'm able to create session in device when user signin.I am using boto3 library for that.

I want to create each user seperate iot-group,and able to publish and subscribe topics in group.How to 
create group and how to download rootCA,private key key for iot group using boto3?

**Comment by liuszeng** [comment]
Hi @jay7583 ,

This sounds like a AWS IoT control plane related question. You may want to put the question in the AWS SDK for Python (boto3) repository (https://github.com/boto/boto3) or AWS Forums for IoT (https://forums.aws.amazon.com/forum.jspa?forumID=210) to get better support.

Thanks,
Liusu
