### ISSUE TITLE
MQTT client timing out in subscribe()

### ISSUE THREAD

**Issue by tyoungNIO** [aws/aws-iot-device-sdk-python#138]
An instance of AWSIoTMQTTClient is not able to subscribe to topics, raising `AWSIoTPythonSDK.exception.AWSIoTExceptions.subscribeTimeoutException` after the configured timeout. The topic can be replaced with any arbitrary string and the same exception is raised. I'm following this repo's README [verbatim](https://github.com/aws/aws-iot-device-sdk-python/blob/master/README.rst#awsiotmqttclient) so I won't bother to paste my code here, all calls to subscribe() timeout. What am I missing?

**Comment by vareddy** [comment]
Hi @tyoungNIO,
Thank you for your interest in the AWS IoT SDK. 
Are you using certificates to connect to AWS IoT? If yes, could you check if the policy that is attached to your thing certs allows subscriptions? The failure you are seeing is after the connect call succeeds, I assume?
Thanks!
Vaurn

**Comment by tyoungNIO** [comment]
Thank you for the quick reply and great insight, your assumption is correct and my policy document for this certificate looks like this:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:Connect",
      "Resource": "*"
    }
  ]
}
```
Clearly I have  [more documentation](https://docs.aws.amazon.com/iot/latest/developerguide/iot-policies.html) to read. Thank you!

**Comment by rubambiza** [comment]
@vareddy @shadetree01010100 Thank you both for this thread. I am new to AWS IoT, and I ran into a similar error trying to follow a [tutorial](https://docs.aws.amazon.com/iot/latest/developerguide/iot-moisture-tutorial.html) on working with AWS IoT Things. My certificate policy document, which I copied from [here](https://docs.aws.amazon.com/iot/latest/developerguide/iot-moisture-policy.html) and replaced the region with us-east-2 and my AWS account number, does allow subscriptions. For more context, it is the shadowDelete operation  from the [example script](https://docs.aws.amazon.com/iot/latest/developerguide/iot-moisture-raspi-setup.html) that runs into the `subscribeTimeoutException` error. The traceback is below. I have tried:

- Removing and re-adding any prior email subscriptions for SNS tied to the thing (A Raspberry Pi 4B)
- Double checking my policy document
- Checking the accuracy of my endpoint name (this helped with a prior connection error), certificate name, private key, clientID, etc

Any guidance on what to look out for next would be much appreciated. Thanks.

```
Traceback (most recent call last):

  File "moistureSensorTest.py", line 143, in <module>
    deviceShadowHandler.shadowUpdate(json.dumps(payload), customShadowCallback_Update, 5)

  File "/home/pi/.virtualenvs/<insert_env_name>/lib/python3.7/site-packages/AWSIoTPythonSDK/core/shadow/deviceShadow.py", line 360, in shadowUpdate
    self._shadowManagerHandler.basicShadowSubscribe(self._shadowName, "update", self.generalCallback)

  File "/home/pi/.virtualenvs/<insert_env_name>/lib/python3.7/site-packages/AWSIoTPythonSDK/core/shadow/shadowManager.py", line 70, in basicShadowSubscribe
    self._mqttCoreHandler.subscribe(currentShadowAction.getTopicAccept(), 0, srcCallback)

  File "/home/pi/.virtualenvs/<insert_env_name>/lib/python3.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 306, in subscribe

    raise subscribeTimeoutException()

AWSIoTPythonSDK.exception.AWSIoTExceptions.subscribeTimeoutException
```

**Comment by sqnidea** [comment]
Hello guys, currently I am facing this error. deployed my app in render. However, as per researching It seems the problem is not on the render. Because it is working fine locally.

**Comment by jmklix** [comment]
@sqnidea can you open a new issue and include more details about the error you are getting and a minimal reproduction sample?
