### ISSUE TITLE
Certificate subject does match remote host name, AWS IOT greengrass and AWS IOT core

### ISSUE THREAD

**Issue by raz08** [aws/aws-iot-device-sdk-python#140]
It clearly says certificate does not match. But why? I'm not sure. I have created greengrass and device in that, It was working fine end to end (device to greengrass to cloud AWS iot) . But when I changed my network i.e. switched wifi. Then server rejected my my certificate with mentioned error. 

Trying from last two days. Please help me in fixing this. I'm new to certificate based security.

Thanks

**Comment by JonathanHenson** [comment]
We'd need a lot of information about your certificate to say for sure (for example, an SSL dump?)
