### ISSUE TITLE
Failure to reconnect when network restored

### ISSUE THREAD

**Issue by codesqueak** [aws/aws-iot-device-sdk-python#142]
Release 1.4.0

Platform Raspberry Pi Zero

I have an application based on the async example.  The program connects and sends data without issue.  

However, if I the network is lost and then restored, the application appears to fail to detect the network availability and remains in offline mode.

2018-07-28 09:54:29,541 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing async publish...
2018-07-28 09:54:29,550 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Offline request detected!
2018-07-28 09:54:29,558 - AWSIoTPythonSDK.core.protocol.internal.queues - DEBUG - append: Add new element: <AWSIoTPythonSDK.core.protocol.internal.requests.QueueableRequest object at 0xb65641f0>

Any hints on what may be wrong ? how to fix this issue ?

Any help appreciated !

**Comment by JonathanHenson** [comment]
does it ever recover, but just take a long time? Or does it not recover at all?

**Comment by codesqueak** [comment]
It never connects.  The only way out I have found is to restart the
application.

**Comment by sharpk** [comment]
I can confirm I've seen this same issue running with version 1.4.5 on a BeagleBone Black.

It never reconnects.

**Comment by zacharyfox** [comment]
Having this same problem with 1.4.7. Easily reproduced. Start subscriber and unplug / replug network cable.

```
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:stableConnection: Resetting the backoff time to: 1 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.internal.workers:Produced [disconnect] event
DEBUG:AWSIoTPythonSDK.core.protocol.internal.workers:Produced [disconnect] event
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 1 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.internal.workers:Dispatching [disconnect] event
DEBUG:AWSIoTPythonSDK.core.protocol.internal.clients:Invoking custom event callback...
INFO:root:MQTTClient.onOffline called
DEBUG:AWSIoTPythonSDK.core.protocol.internal.workers:Dispatching [disconnect] event
DEBUG:AWSIoTPythonSDK.core.protocol.internal.clients:Invoking custom event callback...
INFO:root:MQTTClient.onOffline called
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 2 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 4 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 8 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 16 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 32 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 32 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 32 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 32 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 32 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 32 sec.
DEBUG:AWSIoTPythonSDK.core.protocol.connection.cores:backOff: current backoff time is: 32 sec.
```

Never seems to actually try to reconnect, never calls onOnline, just keeps logging the backoff time message.

**Comment by graebm** [comment]
I'm trying my best to reproduce this, but cannot.
I have a Pi3, connected through wireless. I'm using the latest release (1.4.8). I'm running the basicPubSub sample, with the publishing and subscribing logic commented out, so it's just establishing a connection doing nothing. I'm passing keepAliveIntervalSecond=3 to connect() so that connection losses are detected quickly.

If I turn wifi off on the Raspberry Pi, then the connection loss is detected and it starts trying to reconnect.
When I turn wifi back on, the next reconnect succeeds for me
I'm toggling the wifi off and on and the reconnect succeeds each time.

Are you sure that the network connection is in fact working after you've plugged the cable back in? Can you ping external hosts?

Do you see the same behavior if you run your software on a different hardware platform, like your PC?

**Comment by zacharyfox** [comment]
Yeah, I don't have an example of this redacted enough to post publicly. My use case is using MQTT on containers (API nodes) that communicate with IOT devices in the field. If it makes any difference, I was running the subscriber in a process I never join that basically does subscribe and while True: sleep(1)

Note: My fix for this was to simply implement my own wrapper around paho.mqtt.client myself. I couldn't figure out what this library was trying to do or where it was failing to handle those errors.
