### ISSUE TITLE
offline publish queue size ignored

### ISSUE THREAD

**Issue by pocket5s** [aws/aws-iot-device-sdk-python#144]
I set up a test client using the basicPubSub example as a base. when I set the offline queue size via:

myAWSIoTMQTTClient.configureOfflinePublishQueueing(0)

to any number zero or greater, the value is ignored and all messages get sent. For my test I'll get the client running with it publishing a message every 60 seconds. I'll turn off my internet connection (laptop wifi), let a few cycles pass, turn the wifi back on and all messages that couldn't get sent are queued up and sent upon the reconnect.

If I understand the docs correctly, it should only queue up a number equal to the value I set in that function call and no more.  In the debug logging, I do see where the code says "Configuring offline requests queueing: max queue size: X".

**Comment by pocket5s** [comment]
after some experimentation, it seems this is dependent on the ping time set, which is not obvious from the documentation.  If I set a ping time on the connect() function that is lower than my message threshold (60 seconds), then the queue size comes in to play. Not sure if that is the desired behavior or not, but it was sure confusing

**Comment by JonathanHenson** [comment]
We'll add an item for getting the docs updated. Thanks for your feedback!
