### ISSUE TITLE
shadowRegisterDeltaCallback callback function description wrong in documentation and examples

### ISSUE THREAD

**Issue by didiern** [aws/aws-iot-device-sdk-python#145]
It looks like the API documentation and the examples in the SDK are wrong for the callback function of the shadowRegisterDeltaCallback method.

in documentation and examples:    customCallback(payload, responseStatus, token)
in the code:  something like customCallback(payload, delta/shadow_name, None)

Am I correct?

**Comment by JonathanHenson** [comment]
looking into it

**Comment by kikice010** [comment]
Hello, 
Are there any news on this?

I am trying to reuse the example with shadowRegisterDeltaCallback and what i am facing is that the callback never gets triggered on my physical device running the script when i update the device shadow in AWS console .
