### ISSUE TITLE
Make the connection to AWS work behind proxy

### ISSUE THREAD

**Issue by nbwns** [aws/aws-iot-device-sdk-python#152]
Hi ! 

I'm trying to push data from my Pi to AWS but it never passes the .connect() line and I don't get any errors

`print('Trying to connect to AWS')
myMQTTClient.connect()
print('Connected to AWS')`

I'm behind a corporate proxy and I'm pretty sure that's the problem. 

Is there a solution to pass proxy address and credentials ? 

Thanks,
Nicolas

**Comment by JonathanHenson** [comment]
Could we see some more code for context? What port are you using? Are you using MTLS with a cert and key? Could we get a packet trace?
