### ISSUE TITLE
No connection with mqttclient and aws iot

### ISSUE THREAD

**Issue by arik-le** [aws/aws-iot-device-sdk-python#155]
hi ,

i am trying to connect my rpi3 to aws iot via your sdk , downloaded all certificates and even register CA in the AWS IOT console .
when running the aws "configure a device"  api it connect and work like a charm but when i am running my script in shows : 

> Traceback (most recent call last):
> File "r.py", line 30, in <module>
>     myMQTTClient.connect()
>   File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 485, in connect
>     return self._mqtt_core.connect(keepAliveIntervalSecond)
>   File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 192, in connect
>     self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
>   File "/home/pi/.local/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 219, in connect_async
>     raise e
> ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

my script for now is very simple , only connect and publish : 

from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient
import logging

> myMQTTClient = AWSIoTMQTTClient("123afhlss456")
> myMQTTClient.configureEndpoint("XXXXXXXXXXXXXX.iot.us-east-2.amazonaws.com", 8883)
> myMQTTClient.configureCredentials("/home/pi/rfid/MFRC522-python/aws/rootCA.pem", "/home/pi/rfid/MFRC522-python/aws/RasPi.private.key", "/home/pi/rfid/MFRC522-python/aws/RasPi.cert.pem")
> myMQTTClient.configureOfflinePublishQueueing(-1)# Infinite offline Publish queueing
> myMQTTClient.configureDrainingFrequency(2)# Draining: 2 Hz
> myMQTTClient.configureConnectDisconnectTimeout(10)# 10 sec
> myMQTTClient.configureMQTTOperationTimeout(5)# 5 sec
>  
> #connect and publish
> myMQTTClient.connect()
> myMQTTClient.publish("myTopic", "myPayload", 0)
> myMQTTClient.subscribe("myTopic", 1, customCallback)
> myMQTTClient.unsubscribe("myTopic")
> myMQTTClient.disconnect()
> 

please help me

**Comment by JonathanHenson** [comment]
Most likely the certificate being returned from the server is not in your trust store. If you're using a private CA, I don't see you configuring the ca file in your script. 

Other than that, is there any chance you could post the output of ssldump when running the script?

**Comment by arik-le** [comment]
fixed , thanks that was the problem
