### ISSUE TITLE
Using Shadow Client with MQTT Client

### ISSUE THREAD

**Issue by cnrmck** [aws/aws-iot-device-sdk-python#162]
I am having trouble using the Shadow Client in conjunction with the MQTT client. 

Is there a best practice for this sdk on using the AWSIoTMQTTShadowClient and AWSIoTMQTTClient together? I have seen [this](https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/136) but I do not know if it holds for this SDK, or if the concerns about using only one instance hold here as well. 

If there is an example document like was provided [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/samples/linux/subscribe_publish_sample/subscribe_publish_sample.c) that would probably help immensely.

**Comment by cnrmck** [comment]
I figured it out I believe, I'll answer my own question here and perhaps someone can validate that this is the right solution. Would be nice to have in the documentation since I imagine this isn't uncommon. 

(Sorry for mixing camelCase with underscore_case, I just hateCamelCase #74 ) 

```
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTShadowClient

import logging
import json
import time


# First you need to configure the SDK settings
# Usually looks like this:
aws_iot_mqtt_client = None
aws_iot_mqtt_client = AWSIoTMQTTClient("basicPubSub")
port = 8883
host = "your-aws-host-info.amazonaws.com"
rootCA_path = "./your_creds/root-CA.crt"
private_key_path = "./your_creds/privkey.pem"
certificate_path = "./your_creds/cert.crt"

aws_iot_mqtt_client.configureEndpoint(host, port)
aws_iot_mqtt_client.configureCredentials(rootCA_path, private_key_path, certificate_path)

# AWSIoTMQTTClient connection configuration
aws_iot_mqtt_client.configureAutoReconnectBackoffTime(1, 32, 20)
aws_iot_mqtt_client.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
aws_iot_mqtt_client.configureDrainingFrequency(2)  # Draining: 2 Hz
aws_iot_mqtt_client.configureConnectDisconnectTimeout(10)  # 10 sec
aws_iot_mqtt_client.configureMQTTOperationTimeout(5)  # 5 sec

def topic_callback(client, userdata, message):
    print("MSG RECV:")
    print(json.loads(message.payload.decode('utf-8')))
    print("TOPIC: {}".format(message.topic))
    print()

def shadow_delta_callback(payload, responseStatus, token):
    print("payload ", payload)
    print("responseStatus ", responseStatus)
    print("token ", token)

thing_name = "Bot"
shadow_client_id = "basicShadowDeltaListener"

aws_iot_mqtt_shadow_client = AWSIoTMQTTShadowClient(shadow_client_id, awsIoTMQTTClient=aws_iot_mqtt_client)
# Connect to AWS IoT
aws_iot_mqtt_shadow_client.connect()

# Create a deviceShadow with persistent subscription
deviceShadowHandler = aws_iot_mqtt_shadow_client.createShadowHandlerWithName(thing_name, True)

# Listen on deltas
deviceShadowHandler.shadowRegisterDeltaCallback(shadow_delta_callback)

topic = "sdk/test/Python"

aws_iot_mqtt_client.connect()

while True:
    aws_iot_mqtt_client.subscribe(topic, 1, topic_callback)

```

This _should_ work (or a close version of it) with both the basicPubSub.py --mode='publish' and basicShadowUpdater.py . I've been testing with my own scripts, but this is close enough that it should be possible to get going if any future humans (or benevolent robot overlords) come across this.

**Comment by cnrmck** [comment]
Perhaps @liuszeng, if you have any insight into what the limitations are when using the two together that could be useful. I'm just concerned about gorgonwang0's [comment](https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/136#issuecomment-365100478)

**Comment by stcleezy** [comment]
For what it's worth, you can connect with the AWSIoTMQTTShadowClient  and then access its underlying AWSIoTMQTTClient via _myAWSIoTMQTTShadowClient.getMQTTConnection()

Here's a snippet of my code:

```
_myAWSIoTMQTTShadowClient = AWSIoTMQTTShadowClient(config)
_myAWSIoTMQTTShadowClient.connect()

# access MQTT client like this
_myAWSIoTMQTTShadowClient.getMQTTConnection().subscribe(topic, 0, callback)
```
