### ISSUE TITLE
IoT Jobs: jobDocument omitting keys with "null" value?

### ISSUE THREAD

**Issue by jlucier** [aws/aws-iot-device-sdk-python#163]
First off, I'm not sure this is an issue with this device SDK, but it may be.

I've been experiencing an issues recently that I hadn't noticed before (not sure if it's new) where my device will download a job document and keys that I had deliberately set to "null" are missing.

Here's the document as retrieved by boto3's iot client (i.e. this is the job doc reported by IoT):
```
{
  "script_url": null,
  "reboot_on_failure": false,
  "job_type": "blah",
  "code_url": "${<format_string_for_s3>}",
  "release_name": "blah"
}
```

And here's what the device received:
```
{
    "reboot_on_failure": false,
    "job_type": "blah",
    "code_url": "<filled_in_s3_url>",
    "release_name": "blah"
}
```

I'm not exactly sure why this is happening, but it does so reliably and, as mentioned, this didn't used to occur (~a few weeks back -- today being 9/28/18). Please advise.

**Comment by jmklix** [comment]
Sorry for the late reply, but are you still having problems with null value keys being removed?

**Comment by jlucier** [comment]
@jmklix Sorry to say, but I haven't touched AWS IoT virtually at all since posting this 2 years ago. My company has shifted off of the platform in favor of a custom solution tailored more to our needs.

I can't say whether this is still an issue, nor can I really help explain more details as I have completely forgotten much of what I was experiencing here.

**Comment by AbbasAlibhaiER** [comment]
@jmklix i am still struggling with this issue

**Comment by jmklix** [comment]
@AbbasAlibhaiER can you open a new issue with a detailed description and repro steps

**Comment by AbbasAlibhaiER** [comment]
I have made a new issue here: https://github.com/aws/aws-iot-device-sdk-python/issues/347
