### ISSUE TITLE
Can't subscribe to any topic other than sdk/test/Python from the basicPubSub.py sample

### ISSUE THREAD

**Issue by karrigan777** [aws/aws-iot-device-sdk-python#164]
Dear all experts,
I recently installed aws-iot-device-sdk-Python on my RaspberryPi. From one of the samples, "basicPubSub.py", I was trying to subscribe to the topic "RaspberryPi/t1" but I'm getting a timed-out error

[Error Log ](https://pastebin.com/zZfpq74w)

**Comment by roncaratil** [comment]
Dear all, I have the same problem as described above. Any ideas how to solve it?

**Comment by ColdenCullen** [comment]
Can you please paste the policy you have associated with the key you're using?

**Comment by karrigan777** [comment]
Solved: Didn't mention the topic in the policy document

**Comment by ColdenCullen** [comment]
No problem! And don't forget you can use wildcards in those policies.
