### ISSUE TITLE
Connecting over websockets without root CA?

### ISSUE THREAD

**Issue by raerae7** [aws/aws-iot-device-sdk-python#167]
Is it possible to connect without a root CA, using only an access key id and secret access key?

````
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient

clientId = "my-client-id"
clientEndpoint = "my-client-endpoint"
accessKeyId = "my-access-key-id"
secretAccessKey = "my-secret-access-key"

myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId, useWebsocket=True)
myAWSIoTMQTTClient.configureEndpoint(clientEndpoint, 443)
myAWSIoTMQTTClient.configureIAMCredentials(accessKeyId, secretAccessKey)
myAWSIoTMQTTClient.connect()
````

Should the above code work? It throws "AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException" with no other errors.

**Comment by acdart** [comment]
> It should work fine. The websocket method will use the local devices trusted CA store for validating the endpoint's FQDN. Did you check the policy associated with the key/secret to ensure it has iot:connect permissions?

I have a question.
if i just use mqtt, and how can i configure the clientId?

**Comment by jovelcjose** [comment]
If you are just using mqtt, it uses the certificates(private and public keys) that are given to you while you register your device in AWS IoT along with amazons root certificate.

```
myMQTTClient = AWSIoTMQTTClient("myClientID")
myMQTTClient.configureEndpoint("YOUR.ENDPOINT", 8883)
myMQTTClient.configureCredentials("YOUR/ROOT/CA/PATH", "PRIVATE/KEY/PATH", "CERTIFICATE/PATH")
```

**Comment by jovelcjose** [comment]
> > It should work fine. The websocket method will use the local devices trusted CA store for validating the endpoint's FQDN. Did you check the policy associated with the key/secret to ensure it has iot:connect permissions?
> 
> I have a question.
> if i just use mqtt, and how can i configure the clientId?

 If you are just using mqtt, it uses the certificates(private and public keys) that are given to you while you register your device in AWS IoT along with amazons root certificate.

```
myMQTTClient = AWSIoTMQTTClient("myClientID")
myMQTTClient.configureEndpoint("YOUR.ENDPOINT", 8883)
myMQTTClient.configureCredentials("YOUR/ROOT/CA/PATH", "PRIVATE/KEY/PATH", "CERTIFICATE/PATH")
```

**Comment by jovelcjose** [comment]
Regarding this question, i tried the same code as above, i used an access key and a secret key over mqtt websocket to establish a connection but i get the following exception.

```
Traceback (most recent call last):
  File "test.py", line 322, in <module>
    myAWSIoTMQTTShadowClient.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 1217, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 486, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 195, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException
```
Looking for suggestions

**Comment by delijati** [comment]
This solved it for us https://github.com/aws/aws-iot-device-sdk-python/issues/167#issuecomment-430675269 -> 

> iot:connect permissions?

```
{
    "Version": "2012-10-17",
    "Statement": [
        ... # more permissions
        {
            "Effect": "Allow",
            "Action": [
                "iot:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}   
```

**Comment by rccarper** [comment]
For security reasons, if the above change fixes your issue, we do recommend trying to narrow down the policy to only the necessary permissions.
