### ISSUE TITLE
Ability to pass arguments to customCallback functions

### ISSUE THREAD

**Issue by cnrmck** [aws/aws-iot-device-sdk-python#172]
I have a usecase where I need to be able to pass a client to my callback fn. That client is then used to handle the shadow delta event, however it turns out to be impossible to pass any arguments to the srcCallback. 

This is a very challenging problem to get around, my current solution is to import the variable from another module inside my srcCallback function. This violates good design principles by requiring the software to be highly state-dependent. 

How srcCallbacks are handled now:
` def shadowRegisterDeltaCallback(self, srcCallback):`

with an interface that looks like:
`device_shadow_handler.shadowRegisterDeltaCallback(callback)`

I propose a solution similar to Threading: 
`t = threading.Thread(target=customCallbackFn, kwargs={'x': 1,'y': 2})`

Allowing something like:
`device_shadow_handler.shadowRegisterDeltaCallback(callback, args=[the_client_I_need], kwargs={})`

So that I can define a callback like:
```
def callback(payload, responseStatus, token, the_client_I_need):
    # do stuff
```

**Comment by neilgall** [comment]
Why not just wrap the callback in another function capturing the extra arguments?
```
def register_callback_with_client(shadow_handler, callback, client):
    def callback_wrapper(payload, responseStatus, token):
        callback(payload, responseStatus, token, client)

    shadow_handler.shadowRegisterDeltaCallback(callback_wrapper)
```

**Comment by cnrmck** [comment]
@neilgall Thanks! I got around this somehow, it was a while ago though so I'm not sure what it was. Probably a wrapper function enabled by a decorator to make it pretty and pythony, or maybe I did it with a function attribute of some sort a la:
```python
def callback(payload, responseStatus, token):
    callback.myclient(#whatever

# now client is accessible from inside the function callback because it is an attribute of the callback object
callback.myclient = client
```
