### ISSUE TITLE
v1.4.2 isn't available on pypi

### ISSUE THREAD

**Issue by zapur1** [aws/aws-iot-device-sdk-python#174]
The latest release hasn't been published to pypi see https://pypi.org/project/AWSIoTPythonSDK/#history

It would be good to get it updated as the last release addresses some bugs

**Comment by StefanSmith** [comment]
Was hoping this would be announced at reInvent ;-)

**Comment by danthemantran** [comment]
@liuszeng, are you able to publish this latest release?

**Comment by graebm** [comment]
Version 1.4.2 is now available via pip
