### ISSUE TITLE
Expose LWT methods in AWS client objects

### ISSUE THREAD

**Issue by brokaw** [aws/aws-iot-device-sdk-python#18]
Paho client supports LWT, but they're not directly available in the AWS clients. I have to dig into private objects to get at it, like this:

`AWSIoTMQTTShadowClient.getMQTTConnectio()._mqttCore._pahoClient.will_set`

This should be directly supported, probably in `AWSIoTMQTTClient`

**Comment by liuszeng** [comment]
Hi @brokaw ,

Thank you very much for your interest in AWS IoT Python SDK!

We are actively working on it in one of our internal development branch. Please stay tuned on our future SDK releases.

Thanks,
Liusu

**Comment by liuszeng** [comment]
Addressed in [v1.1.0](https://github.com/aws/aws-iot-device-sdk-python/releases/tag/v1.1.0).
