### ISSUE TITLE
a problem of RPI accessing greengrass core,please help

### ISSUE THREAD

**Issue by northeusunshine** [aws/aws-iot-device-sdk-python#182]
I follow the aws greengrass developer guide to build edge system.
I finished correctly settintg up RPI access AWS IOT cloud as greengrass core.
then i want to use another RPI to connect with RPI greengress core.
I do as the instruction in official guide. but i encounted the following error info with I run helloworld publisher python command:
AWSIoTPythonSDK.core.protocal.internal.workers - DEBUG -Processed offline publish request
AWSIoTPythonSDK.core.protocal.mqttcore - INFO-Performing sync publish...
AWSIoTPythonSDK.core.protocal.mqttcore - INFO-offline request detected
AWSIoTPythonSDK.core.protocal.internal.queunes- DEBUG -append: Add new element: <xxxx>
Published topic hello/world/pubsub: {"message": "hello, world! sent form HelloWorld_Publisher", "sequence":3}
After a while the process will terminated itself.

Please help provide some suggestions how to reslove it.

Many thanks
JACK

**Comment by JonathanHenson** [comment]
any chance we could get a wire log or a packet trace?
