### ISSUE TITLE
Can I return customCallback() to a global variable?

### ISSUE THREAD

**Issue by Juanpsd1224** [aws/aws-iot-device-sdk-python#183]
I'm trying to return a message payload from customCallback(client, userdata, message) function into a global variable to be used in IF statement inside a While loop, but I haven't success. Is it posible?

I use json.loads(message.payload) function to convert JSON format from AWS IoT.

![screenshot_41](https://user-images.githubusercontent.com/46231665/50531399-0c2c7f80-0ad7-11e9-90db-11fd82705f90.png)

Regards

**Comment by graebm** [comment]
You need to tell your function to use the `global` payload variable. Otherwise the function will assume that you intended the variable to be local-only.

```
def customCallback(client, userdata, message):
    global payload
    payload = json.loads(message.payload)
    ...
```
