### ISSUE TITLE
AWS MQTT client takes several hours to recover from network outage

### ISSUE THREAD

**Issue by bruno-beloff** [aws/aws-iot-device-sdk-python#186]
I have an application that incorporates an AWS MQTT client, using the AWSIoTPythonSDK. For the most part, it performs well. 

There is one problem: if the network is unavailable for a long period of time, then the client takes several hours to regain connectivity. For example, if a router is switched off at 5pm and only restored at 9am the next day, then the client will continue to fail to reconnect for around six hours. 

This is easy to test: let's say the router goes back on at 9am. I can ssh to my device at 9am, and watch its syslog (the devices are typically BeagleBones running Debian). The client process will continue to fail to publish for many hours, then eventually succeed. At this point, our data backlog is progressively published.

Settings are:
```
    __KEEP_ALIVE_INTERVAL =         600                     # recommended: 30 default: 600 (sec)

    __PORT =                        8883

    __QUEUE_SIZE =                  -1                      # recommended: infinite
    __QUEUE_DROP_BEHAVIOUR =        MQTTLib.DROP_OLDEST     # not required for infinite queue
    __QUEUE_DRAINING_FREQUENCY =    2                       # recommended: 2 (Hz)

    __RECONN_BASE =                 1                       # recommended: 1 (sec)
    __RECONN_MAX =                  128                     # recommended: 32 or 128 (sec)
    __RECONN_STABLE =               20                      # recommended: 20 (sec)

    __DISCONNECT_TIMEOUT =          10                      # recommended: 10 (sec)
    __OPERATION_TIMEOUT =           10                      # recommended: 5 (sec)

    __PUB_QOS =                     1
    __SUB_QOS =                     1
```

Source code is at: 
https://github.com/south-coast-science/scs_core/blob/develop/src/scs_core/aws/client/mqtt_client.py

If the network outage is short (a few minutes) the client recovers quickly. If the outage is long (hours) the recovery is extremely slow.

Has anyone else experienced this?

AWSIoTPythonSDK version is 1.4.2

**Comment by justinboswell** [comment]
Hello!

I spent yesterday disconnecting the SDK basicPubSub sample at different intervals to try to reproduce this. I tried 1, 2, and 4 hr offline periods, and overnight, with the same settings you detail in your ticket. Each time, within ~2 minutes, the client reconnected and drained 2 messages a second for a while.

I looked through the reconnect code, I don't see anything that stands out as immediately problematic, it's a pretty straightforward calculation to schedule attempts. I don't think we've seen any other cases like this, I wonder what is different about the host or network this client is on? Are they caching negative DNS results? Is the connection immediately functional when the router comes back up? Do you see attempts to connect during the dead period after the connection comes back up?

**Comment by bruno-beloff** [comment]
Thank you for your work on this.

Like you, I have not been able to reproduce this on my own network. But it does happen consistently on one remote network, and I have seen it happen on two others. Unfortunately, we do not have access to routers, etc. on those networks.

I can say for certain that the network is functional when I am able to access it. For example, ping google.com always works. I don't know how to test whether the client is attempting a reconnect. I am thinking that I should log this.

My guess is that caching negative DNS results is happening, but I don't know where.

Any more thoughts or experiments would be greatly appreciated.

**Comment by bruno-beloff** [comment]
There seems to be a repeatable issue: the longer the network outage, the longer the publish fail time is following network restoration. Is there some sort of exponential back-off for DNS updates somewhere?

**Comment by justinboswell** [comment]
It looks like the DNS results come down to the configuration of the resolver on the host. The only code doing any custom DNS lookups is the code in Client.connect_srv, looking for SRV records based on a domain (or the domain of the current socket).

The only exponential backoff in the codebase is tied to reconnect attempts, which uses the parameters passed to configureAutoReconnectBackoffTime().

I think your best next step is to log when reconnects are tried and why they fail on these affected hosts. That might give us a clue as to why the hosts are offline for so long, despite a seemingly working network connection.

Another thought: are the routers that are unplugged the DHCP servers for their respective networks? If so, any leases which expire while the router is down will result in inconsistent network behavior until the leases are properly renewed (which isn't always instant when the DHCP server comes back).
