### ISSUE TITLE
Question regarding MQTT backoff logic

### ISSUE THREAD

**Issue by alexkohler** [aws/aws-iot-device-sdk-python#189]
While initializing [ProgressiveBackOffCore](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/connection/cores.py#L66), `_currentBackoffTimeSecond` is initialized to 1, despite the comment saying it should be initialized to 0:

```Python
# Current backOff time in seconds, init to equal to 0
self._currentBackoffTimeSecond = 1
```

Moreover, it looks like there's logic inside of `backOff` that relies on `_currentBackoffTimeSecond` being 0.
```Python
if self._currentBackoffTimeSecond == 0:
    # This is the first attempt to connect, set it to base
    self._currentBackoffTimeSecond = self._baseReconnectTimeSecond
```

Because of this, it appears there is no way of configuring `_currentBackoffTimeSecond` until `_connectionStableThenResetBackoffTime` is called. Is this a bug, or am I missing something?

**Comment by JonathanHenson** [comment]
could you provide more context on why you need to configure this value?

**Comment by alexkohler** [comment]
I personally don't have a use case for configuring `_currentBackoffTimeSecond`, I was mostly curious if the current behavior is intentional.
