### ISSUE TITLE
Can't use same string for Client ID and shadowName while using shadowRegisterDeltaCallback

### ISSUE THREAD

**Issue by voostar** [aws/aws-iot-device-sdk-python#19]
While I running the sample of ThingShadowEcho, I had set "Raspberry" for both Client ID and shadowName like following:
`

myAWSIoTMQTTShadowClient = AWSIoTMQTTShadowClient(**"Raspberry"**)

Bot = myAWSIoTMQTTShadowClient.createShadowHandlerWithName(**"Raspberry"**, True)

`
Then the customShadowCallback_Delta function will not works. But for the sample of basicShadow is works for me.

**Comment by liuszeng** [comment]
Hi @voostar ,

Thank you very much for using AWS IoT Python SDK!

One thing you can do it is to verify that the AWSIoTMQTTShadowClient actually subscribes to the shadow delta topic. To do that, you can use the MQTT Client in your AWS IoT Console and [AWS IoT Life Cycle Event](http://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html). In Console MQTT Client, follow the instructions below:
a. Make sure that you are in the same region where your credential is created for the device.
b. Subscribe to `$aws/events/#`.
c. Start the sample script ("Raspberry" as client id and thing name)

Ideally, you should be able to see a `connected` event and a `subscribed` event:

    {
      "clientId": "Raspberry",
      "timestamp": <TIME_STAMP>,
      "eventType": "connected",
      "sessionIdentifier": <SESSION_ID>,
      "principalIdentifier": <PRINCIPAL_ID>
    }

    {
      "clientId": "Raspberry",
      "timestamp":<TIME_STAMP>,
      "eventType": "subscribed",
      "sessionIdentifier": <SESSION_ID>,
      "principalIdentifier": <PRINCIPAL_ID>,
      "topics": [
        "$aws/things/Raspberry/shadow/update/delta"
      ]
    }

Note that `ThingShadowEcho` sample features a shadow delta topic listener which syncs the changes of desired state into reported state. You will need to change only the desired state of the same shadow from other end, i.e., AWS IoT Console, to see delta messages got captured and synced by the sample.

Please let us know how it goes.

Thanks,
Liusu

**Comment by liuszeng** [comment]
Hi @voostar ,

We haven't heard from you for a while. We will close the issue for now. If you have any further questions, please feel free to reopen the issue or start another thread to call out.

Thanks,
Liusu
