### ISSUE TITLE
AWSIoTPythonSDK.exception.AWSIoTExceptions.DiscoveryDataNotFoundException

### ISSUE THREAD

**Issue by jovelcjose** [aws/aws-iot-device-sdk-python#190]
I am trying to run basicdiscovery.py from my windows machine, my green grass core is installed within Raspberry, and i have attached 2 devices to the green grass group.

when i run the  basicdiscovery.py with thingName HelloWorld_publisher, I get the following error.

AWSIoTPythonSDK.exception.AWSIoTExceptions.DiscoveryDataNotFoundException

Python version in windows is 3.7.1

**Comment by JonathanHenson** [comment]
Most likely, this is an authorization issue. Services will often return a 404, not because the resource doesn't exist but because you are not authorized to access the resource. Can you verify the policy your credentials are using?

**Comment by abawchen** [comment]
@JonathanHenson :

Same issue here, and policy as follows:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Subscribe",
        "iot:Connect",
        "iot:Receive"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "greengrass:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

**Comment by abawchen** [comment]
I solved this one by `To manually enter the endpoint` (https://docs.aws.amazon.com/en_us/greengrass/latest/developerguide/test-comms.html?shortFooter=true#corp-network-manual-detection) since I am testing on corporate network.
