### ISSUE TITLE
AWS IoT endpoints not resolved by many default router DNS providers - "Name or service not known"

### ISSUE THREAD

**Issue by eclair4151** [aws/aws-iot-device-sdk-python#192]
I have a service/script which allows people to control their TV using Alexa.
https://github.com/eclair4151/AlexaControlledSamsungTV

It uses this lib to connect over MQTT, and one issue many users get is the following error:

https://github.com/eclair4151/AlexaControlledSamsungTV/issues/21
https://github.com/eclair4151/AlexaControlledSamsungTV/issues/11
https://github.com/eclair4151/AlexaControlledSamsungTV/issues/6
https://github.com/eclair4151/AlexaControlledSamsungTV/issues/4

It can also be seen in previous issues of this lib here, which were closed for inactivity:
https://github.com/aws/aws-iot-device-sdk-python/issues/101
https://github.com/aws/aws-iot-device-sdk-python/issues/133
https://github.com/aws/aws-iot-device-sdk-python/issues/27

```
File "/home/pi/AlexaControlledSamsungTV/helpers/mqtt_server.py", line 247, in startServer
myMQTTClient.connect()
File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 408, in connect
return self._mqtt_core.connect(keepAliveIntervalSecond)
File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 168, in connect
self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 179, in connect_async
rc = self._internal_async_client.connect(keep_alive_sec, ack_callback)
File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/internal/clients.py", line 113, in connect
rc = self._paho_client.connect(host, port, keep_alive_sec)
File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 654, in connect
return self.reconnect()
File "/home/pi/.local/lib/python3.5/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 776, in reconnect
sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
File "/usr/lib/python3.5/socket.py", line 694, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Every single case of this issue is related to the fact their default DNS cant resolve my endpoint and fails to connect. In every case of this I see, getting the user to manually set their DNS on the machine to 8.8.8.8, 8.8.4.4 fixes the issue immediately. 

The problem is I cant be asking all my users to change their DNS settings to use my software. I can't for the life of me figure out why this is an issue or how to fix it. 

This is how the script is connecting which was taken directly from an example here
```
  myMQTTClient = AWSIoTMQTTClient(clientid)
    myMQTTClient.configureEndpoint("afkx1f9takwol.iot.us-east-1.amazonaws.com", 8883)
    myMQTTClient.configureCredentials(".auth/root.pem", ".auth/private.pem.key", ".auth/certificate.pem.crt")
    myMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
    myMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
    myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
    myMQTTClient.configureMQTTOperationTimeout(5)  # 5 sec
    myMQTTClient.connect()
```

Do you have any thoughts or suggestions on how to solve this?

**Comment by CoogyEoin** [comment]
Hi did you every find a solution to this issue? I'm facing the exact same thing and for whatever reason I can get the sample scripts working perfectly but whenever I have the same client configure methods being called in an OOP structure it's freaking out. I have the same script structure as you just being called in a method.

**Comment by eclair4151** [comment]
Nope I never found a solution. I still just have to tell people to change their DNS

**Comment by gadget-man** [comment]
I'm having exactly the same issue with a couple of my customers. Vodafone Broadband seems to be particularly troublesome, but also BT.

**Comment by DavidOgunsAWS** [comment]
Tomer,

This doesn't seem to be an issue specific to the Python SDK as the problem is the DNS name resolution of the host vended by the AWS IoT. Use the AWS support center link in the AWS console and create a new case there to engage in a troubleshooting process.

Thanks,

**Comment by bretambrose** [comment]
There are multiple instances of customer reports with respect to DNS failures (on IOT addresses) on actual devices and having to reconfigure host-level resolution in order to get the IOT endpoints to resolve.  I am resurrecting this as a model use-case for some new DNS functionality I'd like to add to the v2 SDKs. 

In particular, I'd like to add the ability to configure a fallback resolution method when the default host resolver fails (or after a configurable amount of time with no response).  We'll start with dns-over-udp and dns-over-tls; dns-over-https can come later.  I believe that moving to async versions of getaddrinfo (via integration with the platform event loop) is a pre-requisite to this work.

**Comment by GermanBluefox** [comment]
My customers are facing the same problem. I am using node.js SDK. Is there any solutions for that except DNS server change?

**Comment by fluidfred** [comment]
I have the same problem. 
Used 8.8.8.8 and 8.8.8.4 in my router. Still it could not resolve the DNS address after running properly for 10 hours.
