### ISSUE TITLE
Can't use message id from publishAsync when client uses the offline queue

### ISSUE THREAD

**Issue by Cheroukee** [aws/aws-iot-device-sdk-python#196]
In the project I'm working on, we manage messages (persist, follow sent/received status) to ensure that in the event of other failures, no message is lost. 

To do this, our messages are set as "sent, but unconfirmed" upon publishing to a topic. We then use the `ackCallback` from `publishAsync` to match a specific message ID with the messages. 

Upon testing the internet going out, I've noticed two things : 

1. If the offline queue is full or disabled (configured with a 0 size), the publishAsync doesn't return an `int` message Id but rather a fixed message ID with a value of `"QUEUED"` which is not what is expected if the documentation is to be a point of reference. 

1. If the offline queue is enabled, there is no way to know that a specific message from that queue has been sent, as the worker will use the internal client to republish the message. This makes it impossible to retrieve the message ID, rendering the `ackCallback` unuseful.

I'm curious to know what should be my flow here? My current one is to disable the offline queue since it creates a state where my messages are sent but I won't know if they got to destination. Then I just wait until a publishAsync doesn't give me back a `"QUEUED"` to actually set the message status to "sent, but unconfirmed".

**Comment by ColdenCullen** [comment]
To 1. it sounds like the docs need to be updated. We can definitely do that.
to 2. are you saying that ackCallback is not passed a message ID? Or simply that you won't get it until much later (on reconnect)?

BTW why not just use QoS 1 (AT_LEAST_ONCE) to make the protocol do all of this work for you?

**Comment by Cheroukee** [comment]
Using QoS 1 works well to ensure the message gets to destination at least once, and then we handle potential duplicates in our backend.

When using it, added to the offline queue, if a message is queued when it is full, you don't get a  message ID as a response but rather the "QUEUED" string. See this snip of code (taken from mqtt_core.py)

```
def publish_async(self, topic, payload, qos, retain=False, ack_callback=None)
    if ClientStatus.STABLE != self._client_status.get_status():
        self._handle_offline_request(RequestTypes.PUBLISH, (topic, payload, qos, retain))
        return FixedEventMids.QUEUED_MID
    else:
        rc, mid = self._publish_async(topic, payload, qos, retain, ack_callback)
        return mid
```

In case of a successful publish_async, the `mid` that is returned can be used to catch a success in the `ack_callback`. If the queue is full, it will publish to the offline queue with the selected policy (`DROP_OLDEST` or `DROP_NEWEST`) and send when possible, but the aformentioned mid is not available. 

It forces me to use my offline data persistence methods to wait until I am actually able to send instead of queueing.

Otherwise, when the queue is disabled, all is good and it does what expected it to.

**Comment by ColdenCullen** [comment]
Ah I think I see the problem. I'm not sure we'll be able to implement this with how the SDK is currently implemented, but I'll definitely see what I can do.

**Comment by jmklix** [comment]
Sorry, but we were not able to implement this feature request and it is no longer being considered because this sdk is being sunsetted. The [V2](https://github.com/aws/aws-iot-device-sdk-python-v2) sdk is accepting feature requests.
