### ISSUE TITLE
Unknown error when connecting to myShadowClient 

### ISSUE THREAD

**Issue by SatishModugu** [aws/aws-iot-device-sdk-python#198]
Hello,
I am following the tutorial on https://docs.aws.amazon.com/iot/latest/developerguide/iot-plant-step5.html

I am using Python 2.7, When I modify the given code with the keys I have, I am getting the below error:

  File "moisture.py", line 44, in <module>
    myShadowClient.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 1217, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 486, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 192, in connect
    self.connect_async(keep_alive_sec, self._create_blocking_ack_callback(event))
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqtt_core.py", line 219, in connect_async
    raise e
ssl.SSLError: unknown error (_ssl.c:2947)

Please let me know what might be the issue.

**Comment by ColdenCullen** [comment]
Hi there, can you please try the steps listed on troubleshooting page and let us know how that goes? https://docs.aws.amazon.com/iot/latest/developerguide/diagnosing-connectivity-issues.html

**Comment by SatishModugu** [comment]
@ColdenCullen, Thanks a lot for your response. 
I have tried the steps on the troubleshooting page, After giving the command  OpenSSL s_client with the keys I have, Nothing is displayed.
![IMG_0804](https://user-images.githubusercontent.com/32131478/56234149-48fe9100-604a-11e9-851d-63664a86a1f4.jpg)

Please find attached picture for your reference.

**Comment by justinboswell** [comment]
What is the output of ```openssl version```?

**Comment by SatishModugu** [comment]
@justinboswell  Its 1.1.0j  20 Nov2018

**Comment by justinboswell** [comment]
You should have quite a bit of output from ```openssl s_client``` (see below). I see in your screenshot that you are connecting to custom_endpoint.iot.us-east-1.amazonaws.com, you will need to replace custom_endpoint with your actual service endpoint (it will be of the form [alphanumeric identifier]-ats.iot.[region].amazonaws.com).

```sh
➜  ~ openssl s_client --connect <endpoint>-ats.iot.us-east-1.amazonaws.com:8443 -CAfile ~/Downloads/AmazonRootCA1.pem -cert ~/Downloads/my-certificate.pem.crt -key ~/Downloads/my-private.pem.key
CONNECTED(00000003)
depth=2 C = US, O = Amazon, CN = Amazon Root CA 1
verify return:1
depth=1 C = US, O = Amazon, OU = Server CA 1B, CN = Amazon
verify return:1
depth=0 CN = *.iot.us-east-1.amazonaws.com
verify return:1
---
Certificate chain
 0 s:/CN=*.iot.us-east-1.amazonaws.com
   i:/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
 1 s:/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
   i:/C=US/O=Amazon/CN=Amazon Root CA 1
 2 s:/C=US/O=Amazon/CN=Amazon Root CA 1
   i:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
 3 s:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Services Root Certificate Authority - G2
   i:/C=US/O=Starfield Technologies, Inc./OU=Starfield Class 2 Certification Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
...snip...
-----END CERTIFICATE-----
subject=/CN=*.iot.us-east-1.amazonaws.com
issuer=/C=US/O=Amazon/OU=Server CA 1B/CN=Amazon
---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: ECDSA+SHA512:RSA+SHA512:ECDSA+SHA384:RSA+SHA384:ECDSA+SHA256:RSA+SHA256:DSA+SHA256:ECDSA+SHA224:RSA+SHA224:DSA+SHA224:ECDSA+SHA1:RSA+SHA1:DSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA512:RSA+SHA512:ECDSA+SHA384:RSA+SHA384:ECDSA+SHA256:RSA+SHA256:DSA+SHA256:ECDSA+SHA224:RSA+SHA224:DSA+SHA224:ECDSA+SHA1:RSA+SHA1:DSA+SHA1
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 5399 bytes and written 1448 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: C73ECA29EF3736D22E055F1AB6191E9A3C4BF728A7E03AD566B0BF952EF929BB
    Session-ID-ctx: 
    Master-Key: ...snip...
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1555455635
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---

```

**Comment by SatishModugu** [comment]
@justinboswell ..I am new to AWS, Can you please let me know from where I can get the endpoint?

**Comment by justinboswell** [comment]
1) Go to the AWS console, and go to IoT Core where you configured your IoT thing.
2) On the left menu, go to Manage, then Things, and click on the Thing you are working with
3) On the left menu, click on Interact, the service endpoint will be the first thing listed, under HTTPS

**Comment by SatishModugu** [comment]
@justinboswell, Thanks a lot for your response, I have changed the endpoint, Still, nothing is getting displayed as output.

**Comment by justinboswell** [comment]
Can you post the exact commands you ran and the output?

**Comment by justinboswell** [comment]
Also, try adding ```-debug``` to your ```openssl s_client``` command line
