### ISSUE TITLE
ShadowUpdate not updating shadow document from ThreadPool

### ISSUE THREAD

**Issue by Kryptic-Ken** [aws/aws-iot-device-sdk-python#200]
After calling shadowGet, inside of the callback method. I check a value from the payload, then update it, and pass it to a function that executes from my custom thread pool. However, it doesn't seem to be working; the shadow document is not changing when shadowUpdate is called. I am using SDK version 1.4.4.

```
executors = ThreadPoolExecutor(max_workers = 2)

def update(payload = None):
    payload["state"]["desired"]["video"] 
    myDeviceShadow.shadowUpdate(json.dumps(payload),None,5)

def customShadowCallback_Update(payload, responseStatus, token):
    global s3
    global bucket_name
    payloadDict = json.loads(payload)
    command = payloadDict["state"]["desired"]["video"]
    print(command)
    if command == False:
        s3.upload_file('Hello.png',bucket_name,'Hello.png')
        payloadDict["state"]["desired"]["video"] = True
        payloadDict["state"]["desired"]["property"] = 3
        executors.submit(update, kwargs={'payload':payloadDict})

s3 = boto3.client(CREDENTIALS)
bucket_name = BUCKET_NAME
myShadowClient = AWSIoTMQTTShadowClient("myClientID")
myShadowClient.configureEndpoint(ENDPOINT, PORT NUMBER)
myShadowClient.configureCredentials(CREDENTIALS)
myDeviceShadow = myShadowClient.createShadowHandlerWithName(THING NAME, True)
myShadowClient.configureConnectDisconnectTimeout(10)  # 10 sec
myShadowClient.configureMQTTOperationTimeout(5)  # 5 sec
print(myShadowClient.connect(1200)) #Print this out on

while True:
    myDeviceShadow.shadowGet(customShadowCallback_Update, 5)
    time.sleep(5)
```

**Comment by justinboswell** [comment]
The current state of the shadow can be found in the ```state.reported``` section of the document, not ```desired``` (desired is not really meaningful in the response payload, only when updating):
https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-document.html

**Comment by Kryptic-Ken** [comment]
The reported section isn't showing the new state even when I called shadowUpdate on either desired or reported, and it does not seem to be returning a request token upon using the method.

```
def update(payload = None):
    print(payload["state"]["reported"]["video"] )
    print(myDeviceShadow.shadowUpdate(json.dumps(payload),None,5))

def customShadowCallback_Update(payload, responseStatus, token):
    global s3
    global bucket_name
    payloadDict = json.loads(payload)
    command = payloadDict["state"]["reported"]["video"]
    if command == False:
        s3.upload_file('Hello.png',bucket_name,'Hello.png')
        payloadDict["state"]["reported"]["video"] = True
        executors.submit(update, kwargs={'payload':payloadDict})
```

**Comment by justinboswell** [comment]
Looking at the code in your post, you need to set the ```desired``` document to what you want the state to be when calling update, then read from the ```reported``` state, because that is the state of record on the service side.

For more detailed info and guidance, I would suggest reading through https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-data-flow.html

**Comment by Kryptic-Ken** [comment]
Thanks for link; we were able to get the issue resolved.
