### ISSUE TITLE
Error when setting endpoint to port 443 when doing a Greengrass Discovery 

### ISSUE THREAD

**Issue by Jgansaown** [aws/aws-iot-device-sdk-python#201]
Issue: When running Greengrass discovery info provider with port set to 443, attribution error is raised: `'module' object has no attribute 'set_alpn_protocols'`

Only change made to `basicDiscovery.py` is setting the endpoint port to 443.
![image](https://user-images.githubusercontent.com/11676314/56336038-6873f600-61d1-11e9-9316-59b2eea98b7e.png)
Running `basicDiscovery.py` give the following error
![image](https://user-images.githubusercontent.com/11676314/56335939-fd2a2400-61d0-11e9-8b7c-7826bbf48ede.png)

After searching for the error I found that the SSL configuration for enabling APLN is wrong for `DiscoveryInfoProvider` class under the `_create_ssl_connection` function in the file `AWSIoTPythonSDK/core/greengrass/discovery/providers.py`
![image](https://user-images.githubusercontent.com/11676314/56338551-0a4d1000-61dd-11e9-9ecb-2ce1b9fa9a00.png)

To enable APLN you need to use SSLContext, so referencing `AWSIoTPythonSDK/core/protocol/paho/client.py` I made the changes below to `AWSIoTPythonSDK/core/greengrass/discovery/providers.py` 
![image](https://user-images.githubusercontent.com/11676314/56338575-294ba200-61dd-11e9-81f2-666448e343d8.png)

![image](https://user-images.githubusercontent.com/11676314/56338613-47190700-61dd-11e9-9135-932c48a29a82.png)

Which fixes the issue and now I can perform a Greengrass discovery with port 443

**Comment by justinboswell** [comment]
Imported fix and released: https://pypi.org/project/AWSIoTPythonSDK/1.4.6/
