### ISSUE TITLE
myMQTTClient.publish("Mqtt_topic" , MQTT_MSG, 1) always return True

### ISSUE THREAD

**Issue by Thaiph1308** [aws/aws-iot-device-sdk-python#209]
Hi everyone,
Currently, I'm using SDK to sent sensor data (using Raspberry Pi3) to AWS. But the internet and power supply in my location are unstable, I read the SDK and find out that the SDK provides internal Queue to store the MQTT message when myMQTTClient.publish("Mqtt_topic" , MQTT_MSG, 1) Return `False` by config 
```
myMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
myMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
myMQTTClient.configureMQTTOperationTimeout(5)  # 5 sec
```
But because of the unstable of power supply, so that I want to store my data into local Database, so that I using this piece of code:
```
if (myMQTTClient.publish("MQTT_Topic" , MQTT_MSG, 1)) == True:
                    insertToDB("test.db","test_table",str(MQTT_MSG),MQTT_publish = 1)
                    log_sync.info("Success when publish to MQTT topic, Insert MQTT_Message to local database")
                else:
                    insertToDB("test.db","test_table",str(MQTT_MSG),MQTT_publish = 0)
```
MQTT_publish here is using to know if the message is sent to the server = 1 if sent, = 0 if not reach to the server

But when i disable the queue by using this config:
```
myMQTTClient.configureOfflinePublishQueueing(0)  # Disable the queue
myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
myMQTTClient.configureMQTTOperationTimeout(5)  # 5 sec
```
myMQTTClient.publish(""MQTT_Topic , MQTT_MSG, 1) always return True, even the message is reached to AWS or not

Here is the log:
- 2019-05-24 14:25:43,698 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync publish...
- 2019-05-24 14:25:43,699 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Offline request detected!
- 2019-05-24 14:25:43,700 - AWSIoTPythonSDK.core.protocol.internal.queues - DEBUG - append: Queue is disabled. Drop the message: <AWSIoTPythonSDK.core.protocol.internal.requests.QueueableRequest object at 0x73dde6d0>
- 2019-05-24 14:25:43,700 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Offline request queue has been disabled
- 2019-05-24 14:25:48,890 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [connack] event
- 2019-05-24 14:25:48,894 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [connack] event
- 2019-05-24 14:25:48,895 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - No need for recovery
- 2019-05-24 14:25:48,895 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
- 2019-05-24 14:26:03,201 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Produced [disconnect] event
- 2019-05-24 14:26:03,203 - AWSIoTPythonSDK.core.protocol.connection.cores - DEBUG - backOff: current backoff time is: 32 sec.
- 2019-05-24 14:26:03,204 - AWSIoTPythonSDK.core.protocol.internal.workers - DEBUG - Dispatching [disconnect] event
- 2019-05-24 14:26:03,204 - AWSIoTPythonSDK.core.protocol.internal.clients - DEBUG - Invoking custom event callback...
- 2019-05-24 14:26:06,374 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync publish...
- 2019-05-24 14:26:06,375 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Offline request detected!
- 2019-05-24 14:26:06,376 - AWSIoTPythonSDK.core.protocol.internal.queues - DEBUG - append: Queue is disabled. Drop the message: <AWSIoTPythonSDK.core.protocol.internal.requests.QueueableRequest object at 0x73dde210>
- 2019-05-24 14:26:06,376 - AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Offline request queue has been disabled
- 2019-05-24 14:26:29,067 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync publish...
- 2019-05-24 14:26:29,067 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Offline request detected!

I saw `AWSIoTPythonSDK.core.protocol.mqtt_core - ERROR - Offline request queue has been disabled`, so that it mean the `myMQTTClient.publish(""MQTT_Topic , MQTT_MSG, 1)` fail to reach AWS (i'm not sure but i guess that, pls correct if i'm wrong) , but my `MQTT_publish `variable still 1. 
My question is, how can I totally disable the queue function? I'm using Python 2.7 
Thank in advance!

**Comment by justinboswell** [comment]
Looking at the MqttCore, you should be getting an exception since the queue is disabled and you are offline. Have you tried stepping through the ```publish()``` call? What state is the client in? Does it skip the call to ```_handle_offline_request()``` and return ```True```?

**Comment by Thaiph1308** [comment]
Thank you for your reply, currently, I can't work on the PI, I will return in 2 or 3 days later and let you know the details. Very sorry about that :(

**Comment by Thaiph1308** [comment]
I think I fixed the problem.
Before I used this piece of code to keep MQTT connect 
`While Test == True:
           myMQTTClient.connect()
           myMQTT.publish(....)
           time.sleep(3600)
except KeyboardInterrupt:
        test = False
        myMQTTClient.disconnect()
        print('Manual break by user')
        return 0
`
After i changed to 
`While Test == True:
           myMQTTClient.connect()
           myMQTT.publish(...)
           myMQTTClient.disconnect()
           time.sleep(3600)
except KeyboardInterrupt:
        test = False
        myMQTTClient.disconnect()
        print('Manual break by user')
        return 0
`
The log like this one are gone 
`2019-05-31 17:22:31,800 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Performing sync publish...
2019-05-31 17:22:31,801 - AWSIoTPythonSDK.core.protocol.mqtt_core - INFO - Offline request detected!
2019-05-31 17:22:31,803 - AWSIoTPythonSDK.core.protocol.internal.queues - DEBUG - append: Queue is disabled. Drop the message: <AWSIoTPythonSDK.core.protocol.internal.requests.QueueableRequest object at 0x75a69b10>`
That mean, when i connect to MQTT so long without disconnect, maybe it's has some problem ? 

About the client state. I used this piece of code :
`from AWSIoTPythonSDK.core.protocol.internal.clients import ClientStatusContainer
myMQTTClient.connect()
client_status = ClientStatusContainer().get_status()
myMQTTClient.publish(...)
client_status = ClientStatusContainer().get_status()
`
And both client status is 0 (IDLE), does it's normal behavior?

**Comment by jovelcjose** [comment]
Hi friend, i am trying to understand your code,
```
While Test == True:
	myMQTTClient.connect()
	myMQTT.publish(...)
	myMQTTClient.disconnect()
	time.sleep(3600)
except KeyboardInterrupt:
	test = False
	myMQTTClient.disconnect()
	print('Manual break by user')
	return 0
```

I understand how you are establishing connection to AWS, but why is it necessary to continuously connect and disconnect to your client. Doing it outside While loop will also provide you with the same result, right ?

**Comment by jtrells** [comment]
> About the client state. I used this piece of code :
> 
> ```
> from AWSIoTPythonSDK.core.protocol.internal.clients import ClientStatusContainer
> myMQTTClient.connect()
> client_status = ClientStatusContainer().get_status()
> myMQTTClient.publish(...)
> client_status = ClientStatusContainer().get_status()
> ```
> 
> And both client status is 0 (IDLE), does it's normal behavior?

I'm not sure if that client.get_status() method actually tells you if your device is connected or not. I had an issue with reconnecting a bit ago; by using the onConnect and onDisconnect callbacks I checked that the device was disconnected for some time and the client.get_status() would always return 0. After fixing the reconnection problem (having non-unique clientIDs), I tested again the client.get_status() and I still got 0s all the time. This last time I was sure the device was always connected again by using the callbacks.

**Comment by jtrells** [comment]
> I understand how you are establishing connection to AWS, but why is it necessary to continuously connect and disconnect to your client. Doing it outside While loop will also provide you with the same result, right ?

I don't think you need to connect and reconnect every time.

**Comment by Thaiph1308** [comment]
> Hi friend, i am trying to understand your code,
> 
> ```
> While Test == True:
> 	myMQTTClient.connect()
> 	myMQTT.publish(...)
> 	myMQTTClient.disconnect()
> 	time.sleep(3600)
> except KeyboardInterrupt:
> 	test = False
> 	myMQTTClient.disconnect()
> 	print('Manual break by user')
> 	return 0
> ```
> 
> I understand how you are establishing connection to AWS, but why is it necessary to continuously connect and disconnect to your client. Doing it outside While loop will also provide you with the same result, right ?



> > I understand how you are establishing connection to AWS, but why is it necessary to continuously connect and disconnect to your client. Doing it outside While loop will also provide you with the same result, right ?
> 
> I don't think you need to connect and reconnect every time.

As I said before, if I keep connecting without disconnect (doing outside the loop), the message maybe failed to reach AWS Broker (especially when I increase the frequency of MQTT.publish). like below, and it causes my logic inside my code to get failed, I don't know why 
```
2019-06-21 06:09:15,830 - AWSIoTPythonSDK.core.protocol.internal.queues - DEBUG - append: Queue is disabled. Drop the message: <AWSIoTPythonSDK.core.protocol.internal.requests.QueueableRequest object at 0x73fb4d70>
```
