### ISSUE TITLE
Publish Payload size of 128 KB

### ISSUE THREAD

**Issue by Venkat2811** [aws/aws-iot-device-sdk-python#21]
Hi,

In http://docs.aws.amazon.com/iot/latest/developerguide/iot-limits.html, it is given that 

"The payload for every PUBLISH message is limited to 128 KB. The AWS IoT service will reject messages larger than this size."

Will this SDK handle this ?

If message size is greater than 128 KB will it be split and published by the SDK ?

**Comment by liuszeng** [comment]
Hi @Venkat2811 ,

Thank you very much for reaching out.

There is a 128 KB limit for the maximum MQTT payload size for AWS IoT. Any publish request that contains payload larger than this limit will be rejected and result in a disconnect. The AWS IoT Device SDK does not split the message and does publish. If such publish is forwarded to the SDK, SDK client will be disconnected and start the auto-reconnect/progressive back-off process.

Thanks,
Liusu

**Comment by Venkat2811** [comment]
Hi @liuszeng ,

Thanks for explaining.  That helps !

Thanks,
Venkat

**Comment by saeedoraji** [comment]
Hi @liuszeng
if we have messages larger than 128 what's your suggestion to publish it to aws iot?
I wanna to send a file that is greater than 1M

**Comment by markthegrea** [comment]
Is there a specific exception that is thrown that we can look for?

**Comment by bretambrose** [comment]
Unfortunately no.  There are many different circumstances where the Iot service may simply hang up the connection without giving a reason, and this is one of them.

**Comment by drowsylogic** [comment]
Has anyone found an elegant solution to this problem?
A simple way to split messages and recombine them once received on the AWS broker?

**Comment by DavidOgunsAWS** [comment]
In rejecting messages larger than 128kb, AWS IoT would not be able to automatically handle and combine messages for any receiving client. If your payload is consistently around or above 128kb, MQTT is likely not your best data transmission method. Consider an out-of-band service like S3, or further discuss by engaging AWS customer support.

Thanks,

**Comment by tetalisrirudra** [comment]
> Is there a specific exception that is thrown that we can look for?

The exception thrown is RequestEntityTooLargeException, when your payload is greater than 128kb.
