### ISSUE TITLE
Recommendation on handling publishTimeoutException

### ISSUE THREAD

**Issue by cnrmck** [aws/aws-iot-device-sdk-python#211]
Visiting [this issue](https://github.com/aws/aws-iot-device-sdk-python/issues/84) I was hoping to find some guidance on how to handle a publishTimeoutException, perhaps a generalized exception wrapper like: 
```python
mqtt_publish(mqttClient, topic, msg, attempt_count = 0, attempt_threshold = 3):
    '''Use mqtt to publish a message, if the connection fails then retry attempt_threshold times'''
    if attempt_count < attempt_threshold: 
        try:
            mqttClient.publish(topic, msg, 1)
        except AWSIoTPythonSDK.exception.AWSIoTExceptions.publishTimeoutException as e:
            attempt_count+=1
            mqtt_publish(mqttClient, topic, msg, attempt_count)
    else:
         mqttClient.publish(topic, msg, 1)
```

I didn't find a recommendation to that effect, plus it seems as though publishTimeoutException could have broader meaning than just, "Server connection timed out" for example by too large of a message (> 128 KB). 

Would the above pseudocode be an acceptable way to generalize the exception handling, or is there more to the publishTimeoutException that ought be accounted for?

**Comment by bretambrose** [comment]
I'm not very familiar with the v1 SDKs so I'll make some inquiries to see if anyone else has any recommendations.

Just skimming the code, going from recursive to a while loop might be a bit clearer.  I would also consider adding logging so that you can determine if you ever get fail-then-success (as opposed to always just succeeding immediately or failing repeatedly).  That would let you know that the loop was actually useful.

**Comment by KaibaLopez** [comment]
Hi @cnrmck, going through older issues and wanted to know if you are still interested in this?

**Comment by cnrmck** [comment]
Yes, still interested. 

I have not implemented any particular code to handle the issue. 

It seems that perhaps this function coupled with the offline queue could cause duplicate message delivery (without setting the dup flag) a so I have not implemented this in case I want to filetee duplicate messages on my broker side. 

Really the question is still open considering the publishTimeoutException is such a broad error.

**Comment by mluis** [comment]
+1

**Comment by jmklix** [comment]
As stated by bretambrose a while loop would be an ideal way to handle publishTimeoutException. Currently the sdk does not indicate when a message is too large and because of that I'm changing this issue to a bug.

**Comment by delijati** [comment]
This is all not really helpful. We do a reconnect via `retry` decorator. The problem we are facing is:

- We receive a message OK -> send `puback` get no response -> publishTimeOut -> retry 
- This leads to the problem that our client thinks he needs to retry it -> endless loop

This happens from time to time. I assume AWS IoT fails sometimes to deliver or to process the message on time (Just try provisioning a bit more ;)). It would be nice to have AWS IoT server logs, so it can prove me wrong.

**Comment by jmklix** [comment]
You can use [CloudWatch](https://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html) to determine what is causing AWS IoT to fail. Please attach the CloudWatch logs (with any sensitive information removed) so we can try to diagnose your problem.
