### ISSUE TITLE
Register callback on Connect to get "session-present" flag status

### ISSUE THREAD

**Issue by pratapakishore** [aws/aws-iot-device-sdk-python#213]
@liuszeng - I tried your method of creating custom call back method but it is not working out. Could you please send us any sample code snippet of what changes do we need exactly on each file so that it will be helpful. We actually need this persistent message option to be enable in AWSIoTPython library. #35

**Comment by bretambrose** [comment]
Are the on_online and on_offline callbacks (overridable in mqtt_core.py) insufficient for what you're trying to accomplish?

**Comment by pratapakishore** [comment]
no we are actually trying to use persistent message option for that I need to get callback for on_connect and set 'session present' flag to 1. I believe that is the only way to achieve that. that is the main reason I asked specifically for on_connect callback

**Comment by bretambrose** [comment]
Reading the code it appears that the low-level paho client's on_connect and on_disconnect callbacks invoke on_online and on_offline.
