### ISSUE TITLE
How to get all thing shadows?

### ISSUE THREAD

**Issue by atyshka** [aws/aws-iot-device-sdk-python#219]
I would like to query all thing shadows to display on a front end and I can't seem to find anything about this in the API reference. There are functions to interact with a single thing by name, but if the name of a thing is not known, there must be some way to query all available things. Is this possible with the Python SDK?

**Comment by justinboswell** [comment]
This SDK is for clients/devices. The IoT Core API does have the concept of Groups, which you can use to organize, enumerate, and interrogate Things and their state: https://docs.aws.amazon.com/iot/latest/developerguide/thing-groups.html

**Comment by atyshka** [comment]
Alright, sorry it wasn’t initially clear that the sdks are intended for devices only. For a general client app, would the general AWS Python SDK Boto3 be more appropriate?

**Comment by justinboswell** [comment]
Yes, that is the usual SDK for service access.
