### ISSUE TITLE
"No Access Key/KeyID Error"

### ISSUE THREAD

**Issue by gergo2007** [aws/aws-iot-device-sdk-python#22]
Hi

I'm getting a raise ValueError("No Access Key/KeyID Error") ValueError: No Access Key/KeyID Error
but i have my key configured by aws configure.

No handlers could be found for logger "core.util.sigV4Core"
Traceback (most recent call last):
  File "./awshome.py", line 53, in <module>
    iot = createIoT()
  File "./awshome.py", line 43, in createIoT
    iot.connect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 710, in connect
    return self._AWSIoTMQTTClient.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/MQTTLib.py", line 355, in connect
    return self._mqttCore.connect(keepAliveIntervalSecond)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/mqttCore.py", line 282, in connect
    self._pahoClient.connect(self._host, self._port, keepAliveInterval)  # Throw exception...
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 655, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 788, in reconnect
    self._ssl = wssCore.securedWebsocketCore(rawSSL, self._host, self._port, self._AWSAccessKeyIDCustomConfig, self._AWSSecretAccessKeyCustomConfig, self._AWSSessionTokenCustomConfig)  # Overeride the _ssl socket
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/protocol/paho/securedWebsocket/securedWebsocketCore.py", line 170, in __init__
    raise ValueError("No Access Key/KeyID Error")
ValueError: No Access Key/KeyID Error

aws configure
AWS Access Key ID [****************OVGA]:
AWS Secret Access Key [****************Rzja]:
Default region name [us-east-1]:
Default output format [None]:

**Comment by liuszeng** [comment]
Hi @gergo2007,

Thank you very much for using AWS IoT Python SDK!

The SDK will check the following places to find IAM credentials when connecting to AWS IoT using MQTT over WebSocket. The SDK will use the first set of IAM credentials it found to start the connection. (See [here](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/util/sigV4Core.py#L74))
a. Custom IAM configuration
This is configured via API [`configureIAMCredentials(...)`](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/MQTTLib.py#L118) in case you need to change the IAM credentials at runtime, e.g., using Cognito.
b. Environment variables
The SDK will check the following environment variables:

    AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY
    AWS_SESSION_TOKEN

c. Shared credential file
The SDK will check the **default** profile of the shared credential file created via `aws configure`. The shared credential file is by default located at `~/.aws/credentials`.

`ValueError("No Access Key/KeyID Error")` means that no IAM credentials can be found in any of the places mentioned above.

There are several things you can do here:
a. Verify that you have IAM credentials configured via `aws configure` using default profile at the default location. Check if you have a file as `~/.aws/credentials` containing the following information:

    [default]
    aws_access_key_id = <YOUR_AWS_ACCESS_KEY_ID>
    aws_secret_access_key = <YOUR_AWS_SECRET_ACCESS_KEY>
    ...

b. Enable SDK logging and see what is the output.

Please let us know how it goes.

Thanks,
Liusu

**Comment by gergo2007** [comment]
Hello
Thank you for the reply.
I have checked, ~/.aws/credentials is not existing, but I configured it via aws configure:

root@raspberrypi:~/.aws# aws configure
AWS Access Key ID [****************OVGA]:
AWS Secret Access Key [****************Rzja]:
Default region name [us-east-1]:
Default output format [None]:

A config file can be found in the ~/.aws/ location:

[default]
region = us-east-1
aws_access_key_id = XXXXXXXXXXXXXOVGA
aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXzja

**Comment by liuszeng** [comment]
Hi @gergo2007,

Thank you for providing this information.

Usually, AWS CLI will store profile information and credentials in two separate files. For `region` and `output`, a `config` file will be created at `~/.aws/`. For credentials (key and key id), a `credentials` file will be created at `~/aws/`. For more information, please check the AWS CLI [documentation](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-config-files).

One thing you can do is to change the `config` to `credentials` so that SDK can pick it up and proceed. Or you can remove the file and do `aws configure` again. Can you specify the steps you followed to configure the credentials using AWS CLI?

Thanks,
Liusu

**Comment by gergo2007** [comment]
Hello
I renamed the config to credentials and it works now.
I used the following:
sudo aws configure 
AWS Access Key ID [None]: AKIAIOSFODNN7EXAMPLE 
AWS Secret Access Key [None]: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY 
Default region name [None]: us-east-1 
Default output format [None]: ENTER (aka empty)

**Comment by liuszeng** [comment]
Hi @gergo2007 ,

Thank you very much for providing the information. Can you try remove the files and do `aws configure` again to see if two files (`config` and `credentials`) are created?

Also, IAM credentials are critical credentials to access your AWS account. Please do not expose it in public places. I strongly recommend you to deprecate it and regenerate another pair.

Thanks,
Liusu

**Comment by gergo2007** [comment]
Yes, now the two files were created after removing and running aws configure again.

The IAM credentials that you removed from my post above was not my real one, they both ended in EXAMPLE, but thank you for the safety tip!

**Comment by artie88** [comment]
Hi liuszeng,

I have the same problem. Even I have config, credentials files in ~/aws folder.
And when I use "aws iot list-things" command, it works fine. 
I can't figure out how I can solve this.
Please guide me.

Thank you,
