### ISSUE TITLE
basicPubSub does not catch message with other certification and private key than very first ones

### ISSUE THREAD

**Issue by setosato** [aws/aws-iot-device-sdk-python#220]
I tried first AWS IoT. Using first-created certification and private key, basicPubSub.py on Raspberry pi3B+ worked well.
Prroblem is that "It does not work well with the other certifications I made on AWS IoT console later"
Connection and publishing to any topic is successful (confirmed on AWS IoT console) , and subscribing does not raise any error. But it catch no message.
Do I need change coding depending on certifications?

**Comment by justinboswell** [comment]
Can you show some sample code and/or your IAM policy? Perhaps some log output from the sample or your code?

Did you change the client ID? Did you change the topic you are subscribing/publishing to? Are you waiting for the suback before publishing?

**Comment by swarren** [comment]
I had this exact same issue and was scratching my head for a couple of hours; using a single sample app instance would work, but as soon as I started a second instance, using a different client certificate, the first would be forcibly disconnected. Passing the `-id` parameter to the sample app, with a different value for each instance, fixed the issue.

So question: The client certificate *is* the client's identity. Why doesn't AWS identify the device based on that, and not need any client ID passed. Alternatively, why doesn't the sample app take the client ID from the client certificate? Then, everything would "just work".

**Comment by setosato** [comment]
@justinboswell 
> Can you show some sample code and/or your IAM policy? Perhaps some log output from the sample or your code?
This is source code I use.
I insert configurations into line 62-76 so this one work with no parameters.
In this config message of the topic "sdk/test/Python"  does not come.
Using the config commented out I receive the message.
Difference is only client ID and certification.
There is no error raised in both config. If IAM policy is inappropriate, I should see some error.
<script src="https://gist.github.com/setosato/90d9a4336b5695a2d400804c4110ec23.js"></script>

And this is log.
<script src="https://gist.github.com/setosato/2a2b709b933962768c416d3520852683.js"></script>

> 
> Did you change the client ID? Did you change the topic you are subscribing/publishing to? Are you waiting for the suback before publishing?
I change client ID by certification. I did not change topic. and publishing is after suback.

**Comment by justinboswell** [comment]
> I had this exact same issue and was scratching my head for a couple of hours; using a single sample app instance would work, but as soon as I started a second instance, using a different client certificate, the first would be forcibly disconnected. Passing the `-id` parameter to the sample app, with a different value for each instance, fixed the issue.

This is documented (albeit, not super clearly) in the [service limits](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot) for AWS IoT. 

> So question: The client certificate _is_ the client's identity. Why doesn't AWS identify the device based on that, and not need any client ID passed. Alternatively, why doesn't the sample app take the client ID from the client certificate? Then, everything would "just work".

You can have multiple clients share a cert (for instance, it's completely reasonable to have multiple devices from the same user/company share a cert). Thus, 1:1 cert:client isn't a safe assumption. Client ID is intended to allow your app to differentiate clients outside of cert authentication.

**Comment by justinboswell** [comment]
@setosato The code looks fine at a glance. When you made the new Cert/Key set, can you post the policy that you bound to that Thing? 

When there are policy failures, those most often manifest as hangups by the service, you don't get an error or much information unfortunately. I can't tell anything from the log, so I'm trying to look for likely places the failure could come from.

**Comment by setosato** [comment]
@justinboswell 
> @setosato The code looks fine at a glance. When you made the new Cert/Key set, can you post the policy that you bound to that Thing?

Policy attached on new Cert is this:
I put * on Connect, Publish, and Subscribe to avoid policy failure.
https://github.com/setosato/myprivatecode/blob/33b368c0e21e3a2ade31220ea28015b579fd173e/AWS%20IoT%20policyX#L1-L31

> When there are policy failures, those most often manifest as hangups by the service, you don't get an error or much information unfortunately. I can't tell anything from the log, so I'm trying to look for likely places the failure could come from.

I did not know it. I will recheck my policies. Thank you for searching. I will post if something advances.

**Comment by setosato** [comment]
I found out what was wrong.
The policy of certificate of thing need to allow "Receive" action. This allow devices receive message from the MQTT broker.
I do not know why allowing "receive" action is necessary (Is it not enough to allow "Subscribing"?). But anyway allowing "Receive" solved the problem.
policy of certificate of thing below:
https://github.com/setosato/myprivatecode/blob/5aa21759a35049cc67571bf888b5372572645ab1/aws-iot-policy-well-work#L1-L42

Thank you for answering my post. I will close this on Monday.
