### ISSUE TITLE
connect timeout exception 

### ISSUE THREAD

**Issue by PreethamRU** [aws/aws-iot-device-sdk-python#223]
using this code to connect to thing, however, failed to connect. Can you help me with this. Code is below

from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient

myMQTTClient = AWSIoTMQTTClient("random")

myMQTTClient.configureEndpoint("somenumber.ap-south-1.amazonaws.com", 8883)

myMQTTClient.configureCredentials("C:\\Users\\preetham\\Desktop\\awsiot\\root-CA.crt", "C:\\Users\\preetham\\Desktop\\awsiot\\SWM-Preetham.private.key", "C:\\Users\\preetham\\Desktop\\awsiot\\SWM-Preetham.cert.pem")

myMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
myMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
myMQTTClient.configureMQTTOperationTimeout(5)  # 5 sec

myMQTTClient.connect()

while 1:
    myMQTTClient.publish("topic", "myPayload", 1)

**Comment by KaibaLopez** [comment]
Hi @PreethamRU , can you clarify a little, are you getting an error or are you timing out ? What is the code returning?

**Comment by rolandma** [comment]
It's possible that you don't have the correct policy. For demonstration of the python SDK, the policy it automatically created is only allowing several actions, and I had been struggling with the connect timeout too, but then I changed the policy for the thing that I created for the test to the following:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "*"
    }
  ]
}

That fixed my problem.
