### ISSUE TITLE
How to catch exception Websocket Handshake Error while using Cognito Identity

### ISSUE THREAD

**Issue by chung06** [aws/aws-iot-device-sdk-python#224]
I'm trying to connect to AWS IoT by using Cognito Identity (Authenticated Identity), claim temporary IAM credentials then connect, all operation work as normal until network down.
For example, network down for 4 hour and then has internet connection as normal. The problem is temporary credentials cannot refresh while network down (i'm refreshing it inside disconnect callback) and while SDK trying to reconnect when internet connection back, at that time, the IAM credentials has been out dated and it will cause `Websocket Handshake Error`  exception and stuck forever.
So I need help to caught exception when above problem happens in order to refresh IAM and reconnect again.

**Comment by justinboswell** [comment]
Perhaps start trying to get new credentials whenever ```on_disconnect``` happens on the client. Then, when your updated credentials are fetched, feed them back into the client via ```configIAMCredentials```. Then, whenever the next websocket connection is attempted, the new credentials will be used.

**Comment by chung06** [comment]
Thanks for your reply, as I mention on example, the credentials cannot be fetched because network is down, you can imagine the issue as below:
network down --> disconnect callback called (refresh credentials fail, no internet to fetch new credentials) --> retry (during retry, IAM credentials expired) --> network up--> connect with expired IAM credentials --> websocket hanshare error exception
So i need to catch that exception to call connect() again or setup callback (to fetch new IAM credentials) before retry to connect to IoT broker

**Comment by justinboswell** [comment]
Yes, what I'm suggesting is when you receive a disconnect, to start fetching credentials and retry until it succeeds, then update the credentials in the MQTT connection so its next attempt will succeed.

For what it's worth, this problem is not present in our [upcoming v2 version of this SDK](https://github.com/awslabs/aws-iot-device-sdk-python-v2), because all of the events are hookable.

**Comment by chung06** [comment]
Thanks for your suggestion, I think the issue could still happens in some case if the credentials not fetched before internal connection retry inside SDK when internet connection back, for example, fetch credentials function runs after internet back for 2 seconds  but connection retry function runs immediate when internet back.
I'm very interesting in SDK v2, hope it support Cognito Indetity too, I will close this issue if SDK v2 can helps me resole this issue.

**Comment by justinboswell** [comment]
That is possible, the the connection will continue to retry, so it will reconnect successfully once the new credentials are used.

**Comment by yehching0109** [comment]
Hi guys,
I am curious about the "on_disconnect" callback func and the renew credentials for websocket handshake issue.
May anyone of you can provide the sample code of how you fix this issue?
Big thanks,

**Comment by danieldmiller** [comment]
In my case, the issue ended up being that I was passing an invalid argument through `.configureIAMCredentials()`. `credentials_provider.token` was empty for me. 

I was doing:
```
credentials_provider = boto3.Session().get_credentials()
myMQTTClient.configureIAMCredentials(credentials_provider.access_key, 
                                            credentials_provider.secret_key, str(credentials_provider.token))
```


Removing it, and letting the `configureIAMCredentials` default the parameter to `""` internally resolved the issue.
```
credentials_provider = boto3.Session().get_credentials()
myMQTTClient.configureIAMCredentials(credentials_provider.access_key, 
                                            credentials_provider.secret_key)
```
