### ISSUE TITLE
Multiple shadow delta callbacks on a single change

### ISSUE THREAD

**Issue by stcleezy** [aws/aws-iot-device-sdk-python#225]
I am changing two shadow parameters concurrently, enabled and expiration:

`Shadow update accepted: {'state': {'desired': {'license': {'device': {'enabled': True, 'expiration': '2019-10-08T07:00:00.000Z'}}}}, 'metadata': {'desired': {'license': {'device': {'enabled': {'timestamp': 1571096953}, 'expiration': {'timestamp': 1571096953}}}}}, 'version': 278, 'timestamp': 1571096953}`

I would expect a single shadow delta callback via shadowRegisterDeltaCallback. However, I am seeing the delta callback fire twice, one for each change:

`Shadow delta on delta/debug:{"license": {"device": {"enabled": true}}}`
`Shadow delta on delta/debug:{"license": {"device": {"expiration": "2019-10-08T07:00:00.000Z"}}}`

Sometimes, however, this does come across as a single message:

`Shadow delta on delta/debug:{"license": {"device": {"enabled": true, "expiration": "2019-10-08T07:00:00.000Z"}}}`

Is this expected? Accounting for this inconsistency adds a fair amount of complexity, as I need to act on the full object, not just the individual params.

**Comment by bretambrose** [comment]
As you've observed, the Iot Shadow service does not necessarily send atomic updates.  Unfortunately, this isn't something the SDKs can really help with.

**Comment by stcleezy** [comment]
The shadow service _does_ appear to send the object together, as the "Shadow update accepted" comment above demonstrates. I have verified this as well through $aws/things/+/shadow/update/accepted.

The issue appears to be in the SDK's handling of of the shadow _delta_ via the shadowRegisterDeltaCallback. This sometimes sends the whole delta, and sometimes breaks up the object. Is this expected?

**Comment by bretambrose** [comment]
If a single delta-topic update (from the iot service) to a single object is getting split into multiple callbacks then that is not expected.  That being said, I'm not sure how the "Shadow update accepted" demonstrates atomicity.  I was under the impression that "accepted" is the successful acknowledgement returned to the requester, while the actual state change is propagated by messages on a separate delta topic (https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-data-flow.html) and the shadow delta callback is for messages on this separate topic.

**Comment by stcleezy** [comment]
Correct, this is coming through a single Node.js AWS.IoTData service call to updateThingShadow with payload:

`payload:"{"state":{"desired":{"license":{"device":{"enabled":true,"expiration":"2019-10-02T07:00:00.000Z"}}}}}"`

Hence my confusion why the python delta listener fires twice, once for "enabled" and once for "expiration"

**Comment by stcleezy** [comment]
OK, this was 100% a coding issue on our side. We have a race condition between shadow updates, so the suspicious delta was actually correct, in that the other attribute hadn't been updated yet.

THANK YOU for your help!
