### ISSUE TITLE
Unable to update json parameters in device shadow

### ISSUE THREAD

**Issue by MridulAhluwalia** [aws/aws-iot-device-sdk-python#230]
Hi,

I have tried updating the refillSkus parameter in below shadow json. I am able to add additional SKUs like SKU3 adn SKU4 but I am not able to remove the ones which already exist. I have tried to remove them manually from the shadow and I am still not able to.

Please let me know if you need further details to debug or better understand the issue at hand.

{
  "desired": {
    "refillSkus": {
      "SKU1": {
        "skuId": "1",
        "status": "A"
      },
      "SKU2": {
        "skuId": "2",
        "status": "A"
      }
    }
}

**Comment by graebm** [comment]
To remove an entry, you need to publish with an update with the item you want to delete, set to `null`. Ex:
```
{
    "state": {
        "desired": {
            "refillSkus": {
                "SKU1": null
            }
        }
    }
}
```

**Comment by MridulAhluwalia** [comment]
Thanks a lot for your reply. It helped me solve the issue.
