### ISSUE TITLE
Keep alive error

### ISSUE THREAD

**Issue by kilabyte** [aws/aws-iot-device-sdk-python#235]
Im getting the error "mqtt: SERVER: The connection was closed because MQTT keep-alive check failed." Now looking at the mqtt docs and paho i should be able to pass a keep alive arg to the connect function but doing that causes a crash to say it is not a valid argument. Ive also found that this error could be from the payload size being too big? The Node sdk has an property to change the max payload size as well as the keep alive time, does the python have this as well? Any ideas on this error. Using just the default example file but with my filled in server and project settings.

**Comment by graebm** [comment]
Could you please post more of your logs?
I'm searching the python SDK codebase and don't see where an error like
> mqtt: SERVER: The connection was closed because MQTT keep-alive check failed.

might come from. The `keepalive` value can be any number greater than 0. The purpose of this value is tell the client to send regular pings (once every `keepalive` seconds) to the server. The server responds to each `ping` with a `pong`. If the server/client haven't heard from one another in 1.5X this value, they will assume the connection is bad and close it. Then the client will start a new connection. A message saying "keep-alive check failed" probably means that either the client or server hasn't heard from the other in `keepalive * 1.5` seconds, so the connection is being closed.
