### ISSUE TITLE
On Shadow Update callback, identifying the thing that got updated

### ISSUE THREAD

**Issue by erikkanderson** [aws/aws-iot-device-sdk-python#237]
I have a question in regards to having multiple device shadow handlers, each listening to a different thing's shadow. After the device shadow hander is created, I'd like to register the same function for the delta callback (calling .shadowRegisterDeltaCallback). However, when the function that is handling the callback gets called, there is seemingly no way to identify which thing got updated. 

My current method of addressing this problem is to subscribe to the "$aws/things/thing-name/shadow/update/accepted" topic. In the callback function I can use client.topic to learn the thing-name that got updated. However, this method seems a bit ineloquent, and would rather use the device shadow handler. 

Thus my question, Is there a recommended way to use device shadow handlers, and in the callback functions, learn the thing that got updated?

**Comment by bretambrose** [comment]
In other languages, the callback that you submit for the subscribe could be a closure that captures the thing name that you are subscribing against.  That being said, I don't know enough about Python's lambda capture semantics to know if that is a viable approach for you.
