### ISSUE TITLE
The current release is 1.4.8, but the version 1.4.7 is available via the Python Package Index

### ISSUE THREAD

**Issue by tim-seoss** [aws/aws-iot-device-sdk-python#239]
The current release is 1.4.8, but the version which is available via the Python Package Index is still 1.4.7

https://pypi.org/search/?q=AWSIoTPythonSDK

**Comment by KaibaLopez** [comment]
Thanks for pointing this out, I'll look into fixing this.
Also, don't know if you know but, we are sun setting this repo and moving to [V2](https://github.com/aws/aws-iot-device-sdk-python-V2), so you might want to check that out too.

**Comment by swaranga** [comment]
even if there are no more feature development in this repo, at least the latest version which supports the ATS endpoint format should be published pypi. Else the Mqtt client fails to connect
