### ISSUE TITLE
AWS IoT Greengrass Serial Read/Write Failed on Windows 10

### ISSUE THREAD

**Issue by asadali5** [aws/aws-iot-device-sdk-python#242]
[rsrclog(Windows10).txt](https://github.com/aws/aws-iot-device-sdk-python/files/4152596/rsrclog.Windows10.txt)
I'm using aws iot greengrass on windows10 and trying to access local resources and trying to read/write data from serial. i'm following the official documentation of Aws on "ACCESS LOCAL RESOURCES". but i think the lraTest.py code was for ubunutu core not for windows because it include paths.I implemented the functional code instead of using aws management console and deployed the function successfully but after subscription publish to topic doesn't publish anything.

Kindly help me in accessing local resources and to read & write data on serial port on windows 10.

**Comment by asadali5** [comment]
![log](https://user-images.githubusercontent.com/59956425/73734135-fa4bf000-475e-11ea-823c-479be22a097a.PN
[rsrclog(Windows10).txt](https://github.com/aws/aws-iot-device-sdk-python/files/4152572/rsrclog.Windows10.txt)
G)

**Comment by KaibaLopez** [comment]
Hi @asadali5 ,
Can you walk me through your setup? 
I believe that Greengrass Core doesn't run on windows, so I'm kind of assuming that you've setup greengrass core on a ec2 instance or linux device, and running the sdk from a windows machine, but I'd rather not make too many assumptions.

**Comment by asadali5** [comment]
Hi, i have installed greengrass on my windows machine using the docker container, it is running successfully and deploying lambda functions to IoT core using the greengrasssdk. All the actions are performed in no container mode. Now, i want to read/write data from my serial port but the AWS greengrass doesn't support local resources access on windows directly. but it can be through the python functional code. but i don't know python much.  so, if you know how can i access the local and to read the data from serial port directly please do suggest me.

**Comment by KaibaLopez** [comment]
Hi @asadali5 ,
sorry for the late response and more so that I can't be of more help with this... But this is a bit out of the scope of the sdk, so I'll be closing the issue, I hope you've found your solution and again sorry.
