### ISSUE TITLE
Update IOT shadow from EC2 Instance

### ISSUE THREAD

**Issue by istranic** [aws/aws-iot-device-sdk-python#243]
I'm trying to update a device's IOT shadow state from an EC2 instance. My understanding is that I should be able to use IAM Roles attached to the EC2 instance for authentication with AWS IOT. However, I can't seem to figure out the function call for configuring credentials.

I've tried using AWSIoTMQTTShadowClient.configureCredentials() or AWSIoTMQTTShadowClient.configureIAMCredentials() with no inputs, but that errors out. I've also tried to omit the .configureCredentials() function altogether, but I can't connect. 

I also tried supplying access keys locally on my machine via AWSIoTMQTTShadowClient.configureIAMCredentials('ACCESS_KEY_ID', 'SECRET_ACCESS_KEY'), but I get a connection timeout error. I'm using port 443 and useWebsocket is set to True.

The video below suggest that the EC2 instance should pull credentials based on it's attached IAM role automatically, but I'm not sure how to adapt my code to work in that way. 

I feel like I'm fundamentally missing something, so any advice is highly appreciated.

**Comment by istranic** [comment]
Quick Update.

I was able to get this to work by pulling the Role credentials from the EC2 instance using:

creds = json.loads(subprocess.run(['curl', 'http://169.254.169.254/latest/meta-data/iam/security-credentials/DeviceLogic_Role'], stdout=subprocess.PIPE).stdout.decode('utf-8'))

In addion, I had to specify the credentials using:
_self.shadowClient.configureCredentials(rootCAPath)
self.shadowClient.configureIAMCredentials(creds["AccessKeyId"], creds["SecretAccessKey"], creds["Token"])_

However, I though there was a way to get this working without:
1. Specifying the root-CA path
2. Having to pull the credentials explicitly and then inputing them into configureIAMCredentials. I though this happens in the background on the EC2 instance.

**Comment by mrducky4** [comment]
I think the authentication works as you say if you use AWS SDK such as boto3. Maybe it just doesn't work that way with the IoT device SDK.

**Comment by bretambrose** [comment]
The v1 IoT SDKs do not support a lot of the credentials pathways that you may be used to from the regular AWS SDKs.  In particular, I do not think instance metadata or ECS credentials providers are implemented in any of the v1 SDKs.  The v2 SDKs have support for instance metadata and we are in the process of adding support for ECS and instance metadata v2 (a new, more secure workflow within ec2 instances).

**Comment by istranic** [comment]
@bretambrose is the V2 SDK available now or is still in development?

**Comment by bretambrose** [comment]
It is available now: https://github.com/aws/aws-iot-device-sdk-python-v2/
