### ISSUE TITLE
MqttCore.connect should return false instead of raising an exception

### ISSUE THREAD

**Issue by jimmylomro** [aws/aws-iot-device-sdk-python#248]
It is very unclear when a failed client connection should be retried.

Long story short, the call to `AWSIoTPythonSDK.core.protocol.mqtt_core.MqttCore.connect` should only be retried in either of these exceptions: `(operationError, socket.error)`, as when these are raised, `AWSIoTPythonSDK.core.protocol.mqtt_core.MqttCore.connect_async` does a clean up of the event consumer threads.

On the other hand, if no exception is raised in `connect_async` and the call to `event.wait` in `connect` times out then this happens: `raise connectTimeoutException()`, an exception is raised and the event consumer daemon threads are still running, so retrying duplicates the threads by calling `_start_workers` again (which should have a guard to prevent this if you ask me...). Also, it is impossible for the user to determine if the connectTimeoutException will not be raised from an error that actually needs attention.

Instead, the call to `connect` should `return False` as it already returns a True when it succeeds.

Here are some logs showing the bad behaviour (note that when connectTimeoutException was retried, there were two event consumer threads running and this hangs the client connection for some reason):
<img width="1440" alt="logs" src="https://user-images.githubusercontent.com/9936165/78785988-f5462f80-799f-11ea-8685-d9ab3a388a68.png">

**Comment by KaibaLopez** [comment]
Hi @jimmylomro ,
Could you make a PR with the changes you are describing? It would be much clearer for us to review those changes and would be faster to implement them that way too.
