### ISSUE TITLE
Import Failed (python 2.7)

### ISSUE THREAD

**Issue by atyshka** [aws/aws-iot-device-sdk-python#251]
I just installed the sdk via pip, but I can only successfully import it in python3. Attempting to import in Python 2.7, however, yields the following error:

`ImportError: No module named AWSIoTPythonSDK`

**Comment by KaibaLopez** [comment]
Hi @atyshka ,
That is odd, I can't reproduce this. And I'm using:
```
python --version
Python 2.7.17
pip --version
pip 20.0.2 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
```
There may be a problem with your setup, but at least you can get it to work with python 3.

**Comment by atyshka** [comment]
Apologies, `pip` used to be aliased to pip2 on Ubuntu but now it seems it's aliased to pip3. They likely made this change in light of 2.7 EOL. pip2 install command works just fine
