### ISSUE TITLE
Help with Instability on connection

### ISSUE THREAD

**Issue by NervenCid** [aws/aws-iot-device-sdk-python#256]
Hello and sorry for the english:

I'm trying to use AWS IOT with Python i i'm implementing mqtt client:

```
#Exte codigo SOLO SIRVE para escritorio
#NO USARLO en una PYCOM

#
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient 
from pathlib import Path
import time


#
cert_folder=Path("certificados")

# user specified callback function
def customCallback(client, userdata, message):
	print("Received a new message: ")
	print(message.payload)
	print("from topic: ")
	print(message.topic)
	print("--------------\n\n")

# AWS general configuration
AWS_PORT = 8883
AWS_HOST = '*****.amazonaws.com'
AWS_ROOT_CA = cert_folder / "AmazonRootCA1.pem"
AWS_CLIENT_CERT = cert_folder / "*****.cert.pem"
AWS_PRIVATE_KEY = cert_folder / "*****.private.key"

# For certificate based connection
myMQTTClient = AWSIoTMQTTClient("Pycom-client")
# For Websocket connection
# myMQTTClient = AWSIoTMQTTClient("Pycom-client", useWebsocket=True)

# Configurations
# For TLS mutual authentication
myMQTTClient.configureEndpoint(AWS_HOST, 8883)
# For Websocket
# myShadowClient.configureEndpoint(AWS_HOST, 443)
myMQTTClient.configureCredentials(AWS_ROOT_CA, AWS_PRIVATE_KEY, AWS_CLIENT_CERT)
# For Websocket, we only need to configure the root CA
# myMQTTClient.configureCredentials(AWS_ROOT_CA)

myMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
myMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
myMQTTClient.configureMQTTOperationTimeout(50)  # 5 sec

#
if myMQTTClient.connect():
    print('AWS connection succeeded')

myMQTTClient.publish("topic_1", "Hola AWS!!!", 0)

# Subscribe to topic
myMQTTClient.subscribe("topic_2", 1, customCallback)

myMQTTClient.disconnect()

#Ciclo principal
while True:

    myMQTTClient.connect()

    myMQTTClient.publish("topic_1", "Hola AWS!!!", 0)

    # Subscribe to topic
    myMQTTClient.subscribe("topic_2", 1, customCallback)

    myMQTTClient.disconnect()
```

However the connection still is very Instability, i receive an timeout or server rejection messages very often, I can send a couple of meessages and receive some others but is difficult to receive messages via subscription and i don't if i should use additional code in order to improve, i don't know if i must use additional code in order to improve.

Thank you and sorry for the English

**Comment by bretambrose** [comment]
Just a few comments/advice, some or all of which you may already know:

1. Make sure the permissions you've configured within IoT (thing, etc...) are sufficient for the operations you're performing.  If you try to do something that your session configuration hasn't been granted permission to do via policy you will get disconnected.  Sometimes it's easiest to start from wildcard (*) permission and scope downwards.
1. There isn't much, if any, value in continually connecting and reconnecting, especially in a tight loop.  Mqtt the protocol was designed with long-lived, low-bandwidth, spotty-reliability in mind.  The client wrappers around an mqtt connection (in this case, the paho client) all support automatic reconnection.  From an application perspective, a good starting point is connect at the beginning, disconnect at the end and that's that.  If you haven't already, read up on persistent sessions and judge whether or not that's functionality that would improve your application.
1. At least in the sample you provide, the publish topic and subscribe topic are different and so the program will never receive anything.
1. Connecting with the same client id from two different running applications will disconnect the first.  Because the mqtt client will reconnect automatically, this leads to a "disconnect storm" as each client constantly interrupts the other.

Finally, I should also add that AWS IoT has limits around rates and bandwidth on all operations and exceeding them can cause disconnections and failures.

**Comment by NervenCid** [comment]
@bretambrose Thank you for your answer and i beg your pardon for my English:

About the permissions by i used the connection kit provided by Amazon and by i understand they generate the policy automatically, this is file that suppose resume the policy:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Receive"
      ],
      "Resource": [
        "*****:topic/sdk/test/java",
        "*****:topic/sdk/test/Python",
        "*****:topic/topic_1",
        "*****:topic/topic_2"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "*****:topicfilter/sdk/test/java",
        "*****:topicfilter/sdk/test/Python",
        "*****:topicfilter/topic_1",
        "*****:topicfilter/topic_2"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "*****:client/sdk-java",
        "*****:client/Pycom-client",
        "*****:client/sdk-nodejs-*"
      ]
    }
  ]
}
```
If i understand, according the file i'm allowed to Publish and subscribe with that 2 topics, in fact i'm able to publish to make the test and receive some times. But the connection brokes after some time.

About the continuous connecting and disconnecting i don't know if i must use a sleep, but i don't know if i must make the recption of data from the server more explicit.

In the example i'm using the test cliente of Amazon i test first the connection in one way but for example if i publish in my code(topic-1) i subscribe in the server(topic-1), if i publish in the server(topic-2) i subscribe in my code(topic-2) (where i am having the most failures).

About "Connecting with the same client id from two different running applications" i don't understand, so i must use 2 different 'id'? but how will i connect with a backend?

Thank you for all

**Comment by bretambrose** [comment]
I'm not sure what you mean by "connect with a backend" or why having to have unique client ids prevents that.  Client ids are a way of uniquely identifying a particular device.  With AWS IoT it's like you have your own private mqtt broker.  If you have multiple application instances subscribed to the same topic (but connecting with different client ids) they will all receive the messages published to that topic.

**Comment by NervenCid** [comment]
@bretambrose So if i have different id's can i connect to the same topics? but i don't understand if i want more clients connected i must add them in the policy, if i change the client id name, the connection rejected so i used "Pycom-client"

Thank you for your answer

**Comment by bretambrose** [comment]
Your policy can contain wildcards; you're not restricted to specifying single ids.

**Comment by NervenCid** [comment]
@bretambrose Thank you for your answer.

How can i see an example about wildcards? i don't understand

Thats why the continous disconnections?

**Comment by jmklix** [comment]
You can use wildcards to test if it is a policy issue. The following policy allows everything and should only be used to test. Once you get it working you should limit what actions and resources are allowed.
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

This isn't necessarily why the disconnections are happening but will allow us to rule it out as a potential cause.
