### ISSUE TITLE
Support planned for QoS 2?

### ISSUE THREAD

**Issue by cnrmck** [aws/aws-iot-device-sdk-python#259]
Access to QoS 2 would be really useful. 

My server receives several repeat posts from my devices which can be problematic to filter. 

Paho already supports QoS 2. Does aws plan to support QoS 2?

**Comment by bretambrose** [comment]
Qos 2 support is up to the IoT service team.  Honestly, I'm not sure what the best place to +1 a request for it would be, possibly the AWS forums, or an AWS solutions architect if you have a corporate contact.
