### ISSUE TITLE
Aws and same topic for more device

### ISSUE THREAD

**Issue by Bobsilvio** [aws/aws-iot-device-sdk-python#269]
i'm using aws to connect two or more PC, in order to turn them on and off, so i created a virtual device. The problem is that in the same topic, when I switch on, all the devices are switched on also on alexa are called Device1 and device2.
There is a method to identify devices and direct requests, in the same topic.

**Comment by jmklix** [comment]
@Bobsilvio I'm a little confused with how you are implementing it, but you should be able to publish different messages depending on which device you want to turn off. Everything subscribed to a specific topic will receive all messages published to it so the message text needs to be different. If you are still having problems please provide a minimal code sample with what you are trying to do.

**Comment by Bobsilvio** [comment]
ok thanks I would like to know one last thing.
if I give a message from "AA":
myMQTTClient.publish ("myTopic", "myPayload", 0)
and I await the answer from "BB" in a second topic
myMQTTClient.subscribe ("myTopic2", 1, customCallback)
how do i print the response

**Comment by jmklix** [comment]
I'm assuming that you are using the basicPubSub.py when I wrote this answer. To print the response all you need to do is add flush=True to line 32. This only works in [python 3](https://stackoverflow.com/questions/230751/how-to-flush-output-of-print-function).
`    print("--------------\n\n", flush=True)`

Also you can set logging to only show errors on line 82. This prevents the console from being cluttered with all to the debug lines.
`logger.setLevel(logging.ERROR)`

**Comment by Bobsilvio** [comment]
I use https://github.com/thehappydinoa/AshsSDK,  that it uses aws iot.
The purpose is to make alexa recognize virtual devices, let's assume that the skill is public to the user, everyone will read from the same topic, so I'm trying to retrieve the mac address of the devices. Even sending a correct answer does not find the device (perhaps a matter of time, or return)

**Comment by jmklix** [comment]
Could you include more details of what you are trying to do? If your problems are with guide that you linked you might have better luck asking for help there.
