### ISSUE TITLE
clamav with s3

### ISSUE THREAD

**Issue by vikas309** [aws/aws-iot-device-sdk-python#272]
https://engineering.upside.com/s3-antivirus-scanning-with-lambda-and-clamav-7d33f9c5092e#:~:text=Using%20S3%20Event%20Notifications%2C%20a,%2Dstatus%20and%20av%2Dtimestamp%20.

https://github.com/upsidetravel/bucket-antivirus-function

**Comment by vikas309** [comment]
Hye please help me to setup clamav scan for my s3 buckets while uploading any object it must be scan before upload to s3. I also mentioned documentation here bt need help to setup.
Thanks

**Comment by jmklix** [comment]
Sorry but this is the python IoT sdk. We won't be able to help you with that here, but maybe take a look at [widdix](https://aws.amazon.com/marketplace/pp/widdix-GmbH-VirusScan-for-Amazon-S3/B07XFR781T).

**Comment by vikas309** [comment]
can you suggest me where I can get a perfect  sol regarding this?

**Comment by jmklix** [comment]
Try [this](https://www.pentestpeople.com/s3-and-the-anti-virus-scan/)
