### ISSUE TITLE
MQTT Connection time out exception when using Cognito Credentials.

### ISSUE THREAD

**Issue by cepldev** [aws/aws-iot-device-sdk-python#273]
I tried to connect to the AWS IoT MQTT with credentials fetched through a cognito identity and the following exception is received.

```
Connect timed out
Traceback (most recent call last):
  File "C:/Users/Software/Desktop/Test folder for Kivy/mqtt with cognito.py", line 161, in <module>
    myAWSIoTMQTTClient.connect()
  File "C:\Users\Software\Desktop\Test folder for Kivy\venv\lib\site-packages\AWSIoTPythonSDK\MQTTLib.py", line 513, in connect
    return self._mqtt_core.connect(keepAliveIntervalSecond)
  File "C:\Users\Software\Desktop\Test folder for Kivy\venv\lib\site-packages\AWSIoTPythonSDK\core\protocol\mqtt_core.py", line 199, in connect
    raise connectTimeoutException()
AWSIoTPythonSDK.exception.AWSIoTExceptions.connectTimeoutException

Process finished with exit code 1
```

The same code is working when a normal IAM credential is used to connect to the MQTT service.
The policies attached for the Cognito identity and IAM credential are the same(AWSIoTFullAccess).

**Comment by andrewleech** [comment]
Hi, I'm having a similar issue myself, always getting a connect timeout when trying to authenticate using `myAWSIoTMQTTClient.configureIAMCredentials(AccessKeyId, SecretKey, SessionToken)` with credentials from cognito.

Have you made any progress yourself?

**Comment by tallapriyanka0** [comment]
Hello Team,

I'm also facing similar issue, when connecting to MQTT messages using AWSIoTPythonSDK  in python. 

Could you please help me resolving the issue?

**Comment by andrewleech** [comment]
Actually, I did make progress here - the credentials worked fine once I configured the mqtt client to use the root ca certificate from https://docs.aws.amazon.com/iot/latest/developerguide/server-authentication.html : SFSRootCAG2.pem

``` python
myAWSIoTMQTTClient.configureEndpoint(host, 443)
myAWSIoTMQTTClient.configureCredentials('./SFSRootCAG2.pem')
myAWSIoTMQTTClient.configureIAMCredentials(AccessKeyId, SecretKey, SessionToken)
```

**Comment by cepldev** [comment]
> ```python
> myAWSIoTMQTTClient.configureCredentials
> ```

I tried above one using SFSRootCAG2.pem   certificate. But same exception were occuring.

**Comment by jmklix** [comment]
This won't fix the issue if it is a credentials problem, but have you tried increasing the `myAWSIoTMQTTClient.configureMQTTOperationTimeout(5)` to more than 5 seconds?

**Comment by cepldev** [comment]
Commenting to keep the issue open.

**Comment by jmklix** [comment]
@cepldev can you provide some details with how you have it set up including a minimal code snip-it?
