### ISSUE TITLE
Sending image as numpy array over MQTT to greengrassCore

### ISSUE THREAD

**Issue by anubhav1** [aws/aws-iot-device-sdk-python#282]
I am capturing images from webcam and sending those images as numpy arrays to greengrassCore using AWS IoT Device Python SDK. At greengrassCore, this numpy array is transferred to a lamda function for image processing(via RESNET model).

But numpy arrays's size is too big to send over MQTT and thats why greengrassCore is not receiving it.

So is there a way to increase MQTT TX buffer size in SDK? I couldn't find any.

Publishing code :
   ```
    cam = cv2.VideoCapture(0)
    ret, frame = cam.read()
    message['image'] = frame.tolist() #numpy array converted to list to make it work with json.dumps
    messageJson = json.dumps(message)
    myAWSIoTMQTTClient.publish(topic, messageJson, 0)
```

**Comment by jmklix** [comment]
Sorry, but there is no way to increase the maximum message size allowed. As documented [here](https://docs.aws.amazon.com/general/latest/gr/iot-core.html) the maximum message size if 128 KB.

Message size | The payload for every publish request can be no larger than 128                                                 								KB. AWS IoT Core rejects publish and connect requests larger than this                                                 								size.
-- | --

**Comment by anubhav1** [comment]
@jmklix  then how to send an image to greengrass core for "image processing at the edge" as advertised by greengrass core?

**Comment by jmklix** [comment]
I believe that is in reference to using machine learning models to process images with greengrass. For example here is a blog on [How to Install a Face Recognition Model at the Edge Device with AWS IoT Greengrass](https://aws.amazon.com/blogs/iot/how-to-install-a-face-recognition-model-at-the-edge-device-with-aws-iot-greengrass/)

More info can be found in the docs [here](https://docs.aws.amazon.com/greengrass/v2/developerguide/ml-tutorial-image-classification.html).

**Comment by anubhav1** [comment]
These links don't address the issue.

**Comment by jmklix** [comment]
From the greengrass team:
>Greengrass would ideally be on the device taking the pictures and perform image processing then and there (ie "at the edge"). In this case, the webcam would be on the same device as Greengrass. If the you needed to send data to the cloud, you could use Greengrass's stream manager.
>
>However, if you are sending data to the edge through the cloud. You may want to do your inference in the cloud. Either that or you should try to break up your payload into smaller chunks.
