### ISSUE TITLE
shadowUpdate() sends incorrect shadow document due to unsafe thread usage of a member variable

### ISSUE THREAD

**Issue by mrducky4** [aws/aws-iot-device-sdk-python#284]
https://github.com/aws/aws-iot-device-sdk-python/blob/e0f9eef8aafdf6319022d7972d3f1f65eefb784d/AWSIoTPythonSDK/core/shadow/deviceShadow.py#L346

In deviceShadow.py, in shadowUpdate(), it initializes self._basicJSONParserHandler without first locking with self._dataStructureLock. Then another thread, such as a thread handling an incoming shadow delta event, overwrites the value in self._basicJSONParserHandler. Then the thread executing shadowUpdate() acquires the lock, but by then the damage is done and it gets the wrong value in JSONPayloadWithToken and publishes this wrong value.

I have verified, through logging, this actually happening on two different occasions on my devices. Since this SDK is no longer being updated, I won't submit a fix, but I thought other folks might want to know about it.

**Comment by jmklix** [comment]
We are still fixing bugs, security issues, and accepting PR's for this sdk, we just aren't taking feature requests anymore. We would appreciate if you would make a PR including the fix you mentioned above.

**Comment by mrducky4** [comment]
Ok, I will submit a PR.
