### ISSUE TITLE
Respecting the AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by tomca32** [aws/aws-iot-device-sdk-python#287]
Hi everybody,

I was wondering if it is possible to make the SDK respect the AWS_PROFILE environment variable and read from the related profile, if it is set, rather than only reading from the default section.

Currently, the SDK doesn't care about AWS_PROFILE and always reads just the default section of the credentials file.

Thanks

**Comment by jmklix** [comment]
Sorry, but as you noticed this sdk currently doesn't support this and we are no longer taking feature requests for this python v1 sdk. You are welcome to take a look at our [v2 sdk](https://github.com/aws/aws-iot-device-sdk-python-v2) or make a PR on this repo to add support for AWS_PROFILE environment variables.
