### ISSUE TITLE
Register a Thing - Insufficient Permissions

### ISSUE THREAD

**Issue by jonathanrjpereira** [aws/aws-iot-device-sdk-python#288]
I have an AWS Educate account. 
I'm trying to **Register a Thing** but I get the following error:
![image](https://user-images.githubusercontent.com/10046350/114410214-3061dc80-9b79-11eb-94f5-e1a8639da0b6.png)

I'm not sure how to add iot:ListThingTypes permissions to my user policy since I'm not the Admin for the educate account.

**Comment by bretambrose** [comment]
Console questions like this would be best asked on the AWS forums (https://forums.aws.amazon.com/)
