### ISSUE TITLE
Named Shadows not supported

### ISSUE THREAD

**Issue by JGVD21** [aws/aws-iot-device-sdk-python#291]
I've been struggling with the library for a while.

I don't have many comments except that more advanced/named shadow interactions are not supported but the package.

It would be a great addition for devices that require it.

**Comment by jmklix** [comment]
Have you take a look at the [V2 sdk](https://github.com/aws/aws-iot-device-sdk-python-v2)?

Sorry for any inconvenience, but this version will not have any new features added.
