### ISSUE TITLE
ThingShadowEcho doesn't echo shadow changes made in the console

### ISSUE THREAD

**Issue by ianmas-aws** [aws/aws-iot-device-sdk-python#3]
I'm having difficulty getting the ThingShadowEcho sample to work.

The logging output shows a successful connection to my endpoint and successfully subscribing to the topic delta, but it doesn't echo back changes to the shadow that I make via the AWS IoT console.

If the MQTT topic for my updates to my thing shadow is $aws/things/Pi_Py_SDK/shadow/update, what should I change this following line to in order to connect to this shadow and be able to receive shadow updates made via the console?

`Bot = myAWSIoTMQTTShadowClient.createShadowHandlerWithName("Bot", True)`

Hope you can help?

**Comment by liuszeng** [comment]
Hi @ianmas-aws ,

The short answer is yes. You will need to make sure that the ThingShadowEcho sample runs a shadow handler with the same name as the one you are updating through your AWS IoT Console within the same account and same region. In your case it would be:

    myDeviceShadow = myAWSIoTMQTTShadowClient.createShadowHandlerWithName("Pi_Py_SDK", True)

The ThingShadowEcho sample basically creates a shadow handler and listens on its delta topic to receive delta messages. Once there is a difference between the reported state and desired state of this shadow (triggering a delta message), the sample will be able to receive the changes and sync it back to the shadow JSON document as reported state to keep the shadow reported state and desired state in sync.

Let's say you have the following shadow document for "Bot":

    {
        ...
        "state":{
            "desired": {
                "someKey":"someValue"
            },
            "reported":{
                "someKey":"someValue"
            }
        },
        ...
    }

Now the reported state and desired state are in sync. Once you start the sample and make changes to the desired state of this shadow "Bot" from somewhere else, e.g., AWS IoT Console, the JSON document for "Bot" would look like this:

    {
        ...
        "state":{
            "desired": {
                "someKey":"differentValue"
            },
            "reported":{
                "someKey":"someValue"
            }
        },
        ...
    }

On the SDK sample side, it should be able to receive a delta message like this:


    {
        ...
        "state":{
            "someKey":"differentValue"
        },
        ...
    }

Now the sample is aware about the changes in desired state and syncs it back to "Bot" shadow document as reported state. After it is synced, the document should look like this:

    {
        ...
        "state":{
            "desired": {
                "someKey":"differentValue"
            },
            "reported":{
                "someKey":"differentValue"
            }
        },
        ...
    }

You should be able to see in your AWS IoT Console that the "shadow status" is "in sync".

For more information about device shadow messaging, you can check out the documentation here:
http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-data-flow.html

Hope that answers your question and thank you very much for using AWS IoT Python SDK!

Liusu
