### ISSUE TITLE
thread loops on _packet_read

### ISSUE THREAD

**Issue by seuge** [aws/aws-iot-device-sdk-python#30]
Almost same as issue(https://github.com/aws/aws-iot-device-sdk-python/issues/24), but the difference is that the problem happens not exactly when 24 hours after the process started, maybe 1 hour or sometimes couple hours. And when it's happended, it is unable to reconnect to the AWS IoT broker because the disconnect message in packet-queue has no chance to be send. Now i don't know how it happens. Application was ran on CentOS6.5 and python version is 2.7.8.

**Comment by seuge** [comment]
Here is the callstack

**Comment by seuge** [comment]
(gdb) py-bt
#2 (frame information optimized out)
#6 Frame 0x7f46b0dce050, for file /usr/local/python27/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/securedWebsocket/securedWebsocketCore.py, line 69, in read (self=<_bufferedReader(_internalBuffer=<bytearray at remote 0x7f46b1250450>, _remainedLength=1, _sslSocket=<SSLSocket(server_hostname=None, _connected=True, do_handshake_on_connect=True, certfile=None, server_side=False, _makefile_refs=0, _closed=False, suppress_ragged_eofs=True, ciphers=None, ssl_version=2, cert_reqs=2, ca_certs='/home/mqtt/cert/3-Public-Primary-Certification-Authority-G5.pem', _context=<SSLContext at remote 0x7f46b124eb48>, _sslobj=<_ssl._SSLSocket at remote 0x7f46b0db1870>, keyfile=None) at remote 0x7f46b9a456e0>, _bufferingInProgress=True) at remote 0x7f46b0dc25f0>, numberOfBytesToBeBuffered=1, dataChunk='')
    dataChunk = self._sslSocket.read(self._remainedLength)
#9 Frame 0x7f46b0dbc638, for file /usr/local/python27/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/securedWebsocket/securedWebsocketCore.py, line 333, in read (self=<securedWebsocketCore(_maskKey=None, _isFIN=False, _portNumber=443, _payloadDataBuffer=<bytearray at remote 0x7f46b1250960>, _bufferedWriter=<_bufferedWriter(_internalBuffer=<bytearray at remote 0x7f46b1250c60>, _requestedDataLength=-1, _sslSocket=<SSLSocket(server_hostname=None, _connected=True, do_handshake_on_connect=True, certfile=None, server_side=False, _makefile_refs=0, _closed=False, suppress_ragged_eofs=True, ciphers=None, ssl_version=2, cert_reqs=2, ca_certs='/home/mqtt/cert/3-Public-Primary-Certification-Authority-G5.pem', _context=<SSLContext at remote 0x7f46b124eb48>, _sslobj=<_ssl._SSLSocket at remote 0x7f46b0db1870>, keyfile=None) at remote 0x7f46b9a456e0>, _writingInProgress=False) at remote 0x7f46b0dc24d0>, _hasPayloadLengthExtended=False, _hasMaskKey=False, _hasPayloadLengthFirst=False, _hasPayload=False, _hasOpByt...(truncated)
    opByte = self._bufferedReader.read(1)
#12 Frame 0x7f46a4000ff0, for file /usr/local/python27/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py, line 1463, in _packet_read (self=<Client(_tls_certfile=None, _backoffCore=<progressiveBackoffCore(_baseReconnectTimeSecond=1, _resetBackoffTimer=<_Timer(function=<instancemethod at remote 0x7f46b1246320>, kwargs={}, _Thread__ident=139941495351040, _Thread__block=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7f46b1245530>, acquire=<built-in method acquire of thread.lock object at remote 0x7f46b1245530>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7f46b1245530>) at remote 0x7f46b0db1a10>, _Thread__name='Thread-5', _Thread__daemonic=True, args=[], interval=20, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7f46b12454f0>, acquire=<built-in method acquire of thread.lock object at remote 0x7f46b12454f0...(truncated)
    command = self._ssl.read(1)
#15 (frame information optimized out)
#19 (frame information optimized out)
#23 (frame information optimized out)
#27 (frame information optimized out)
#32 Frame 0x7f46b0dc8218, for file /usr/local/python27/lib/python2.7/threading.py, line 763, in run (self=<Thread(_Thread__ident=139941505840896, _Thread__block=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7f46b12454d0>, acquire=<built-in method acquire of thread.lock object at remote 0x7f46b12454d0>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7f46b12454d0>) at remote 0x7f46b0db1910>, _Thread__name='Thread-2', _Thread__daemonic=True, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7f46b1245350>, acquire=<built-in method acquire of thread.lock object at remote 0x7f46b1245350>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7f46b1245350>) at remote 0x7f46b0db1810>) at remote 0x7f46b0db1850>, _Thread__stderr=<file at remote 0x7f46b9b4a1e0>, _Thread__target=<instancemethod at remote...(truncated)
    self.__target(*self.__args, **self.__kwargs)
#35 Frame 0x7f46a4000910, for file /usr/local/python27/lib/python2.7/threading.py, line 810, in __bootstrap_inner (self=<Thread(_Thread__ident=139941505840896, _Thread__block=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7f46b12454d0>, acquire=<built-in method acquire of thread.lock object at remote 0x7f46b12454d0>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7f46b12454d0>) at remote 0x7f46b0db1910>, _Thread__name='Thread-2', _Thread__daemonic=True, _Thread__started=<_Event(_Verbose__verbose=False, _Event__flag=True, _Event__cond=<_Condition(_Verbose__verbose=False, _Condition__lock=<thread.lock at remote 0x7f46b1245350>, acquire=<built-in method acquire of thread.lock object at remote 0x7f46b1245350>, _Condition__waiters=[], release=<built-in method release of thread.lock object at remote 0x7f46b1245350>) at remote 0x7f46b0db1810>) at remote 0x7f46b0db1850>, _Thread__stderr=<file at remote 0x7f46b9b4a1e0>, _Thread__target=<instanceme...(truncated)
    self.run()
#38 (frame information optimized out)

**Comment by liuszeng** [comment]
Hi @seuge ,

Thank you very much for providing the detailed information. We will keep diving into this and try to identify the issue on our side. Will keep you posted.

Thanks,
Liusu

**Comment by seuge** [comment]
Hi @liuszeng  ,
Thanks for your reply. I think it may due to the Chinese GFW that may reset the connection(my deivce is behind the GFW in china), althougth i have no evidence, you can reproduce toward this way. And is there any posibility to recover instead of loop forerver in this scenario?

**Comment by hedeshianaws** [comment]
@seuge I apologize for the inexcusable delay. Are you still seeing this issue with the latest release (v1.2.0)?

**Comment by liuszeng** [comment]
Addressed in v1.3.0.
