### ISSUE TITLE
Register callback on Connect

### ISSUE THREAD

**Issue by lepirlouit** [aws/aws-iot-device-sdk-python#35]
I want to be able to register a callback when connection is established.
For example to send an update on the reported state on startup.

It seems this is possible with the node js sdk like demonstrated in the webinar.

I saw that the mqtt paho lib allow a registration of a callback.

```
import paho.mqtt.client as mqtt
def on_connect(mqttc, obj, flags, rc):
[...]
mqttc = mqtt.Client(client_id="mqtt-test")

mqttc.on_connect = on_connect
```

**Comment by liuszeng** [comment]
Hi @lepirlouit ,

Thank you very much for your interest in AWS IoT Python SDK.

Unfortunately the current version of the Python device SDK does not provide customizable callback registration. The SDK covers the paho callbacks and handles the work behind the scene. We will be adding the feature in future releases. See related issue: 
https://github.com/aws/aws-iot-device-sdk-python/issues/11

As a work-around, you will need to modify the SDK and add your own callback behavior and preserve the SDK callback behaviors at the same time. For more details, you can check out here:
https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/mqttCore.py#L119

Sorry that we cannot provide you with a more positive answer. Please stay tuned.

Thanks,
Liusu

**Comment by lepirlouit** [comment]
If I understand correctly,
I have to add an `self._callbackTable = dict()` in `AWSIoTMQTTShadowClient`

register callback : 
`self._callbackTable["onConnect"] = srcCallback`
and call the callback in the on_connect method, that you point to me ?
```
                    if self._callbackTable.get("onConnect") is not None:
                        processCustomCallback = Thread(target=self._callbackTable["onConnect"], args=[payloadUTF8String, currentType, currentToken])
processCustomCallback.start()
```

**Comment by liuszeng** [comment]
Hi @lepirlouit ,

Yes, you can do that. It depends on the type of client you want to use. The main idea here is, in addition to the on_connect callback behavior that is defined by the SDK, you can add your own customized callback behavior by overriding the original on_connect callback.

To move even further, you can modify the SDK client by creating a public facing handler that allows you to add your own callback behavior more easily, which will be similar to what you suggested. Take `AWSIoTMQTTClient` as an example:

In [mqttCore.py](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/core/protocol/mqttCore.py), make the following changes:

a. Add new data member:

    self._customCallback = dict()


b. Update on connect callback:

    def on_connect(self, client, userdata, flags, rc):
        ...
        if self._customCallback.get("on_connect"):
            self._customCallback["on_connect"](<some args>)  # You can choose to run it in a different thread if you want
        ...

c. Provide a new method to configure the custom callback:

    def addCustomCallback(event, callback):
        self._customCallback[event] = callback
        ...

In [MQTTLib.py](https://github.com/aws/aws-iot-device-sdk-python/blob/master/AWSIoTPythonSDK/MQTTLib.py), expose the APT to configure custom callback:

    def addCustomCallback(event, callback):
        self._mqttCore.addCustomCallback(event, callback)
        ...

In this case, you should have a SDK client that allows you to directly define custom callbacks in your application.

Hope the above helps.

Thanks,
Liusu

**Comment by liuszeng** [comment]
Hi @lepirlouit ,

We haven't heard from you for a while. We are closing the issue for now. If you have any further questions, feel free to reopen it or start a new thread.

Thanks,
Liusu

**Comment by heri16** [comment]
@liuszeng Could we reopen this issue until a pull request is available? The AWS IoT guide specifically mentions that the client should report it's state after a disconnect and reconnect to ensure timely delivery of deltas.

**Comment by pratapakishore** [comment]
@liuszeng - I tried your method of creating custom call back method but it is not working out. Could you please send us any sample code snippet of what changes do we need exactly on each file so that it will be helpful. We actually need this persistent message option to be enable in AWSIoTPython library.

**Comment by stcleezy** [comment]
For reference: 
https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html#AWSIoTPythonSDK.MQTTLib.AWSIoTMQTTClient.onOnline
https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html#AWSIoTPythonSDK.MQTTLib.AWSIoTMQTTClient.onOffline

**Comment by Tejasking** [comment]
hmmm not a relivent code to get data via mqtt and to print to console
