### ISSUE TITLE
Declaring File Path for authentication

### ISSUE THREAD

**Issue by mvsnbharath** [aws/aws-iot-device-sdk-python#37]
I am using Windows 10, I have configured my Access key and Secret ID using AWS Command line.
I have tried to run the basic PubSub example but I get :
Missing '-c' or '--cert'
Missing '-k' or '--key'

The way I am giving input in my command line is:
python basicPubSub.py -e a1vg4xwraxdufo.iot.us-west-2.amazonaws.com -r VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem -c a987d73d1a-certificate.pem.crt -k 987d73d1a-private.pem.key
(and also as)
python basicPubSub.py -e a1vg4xwraxdufo.iot.us-west-2.amazonaws.com -r VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem -c C:\Users\bharath\Desktop\HP\Project\Code\AWS IoT\Python\aws-iot-device-sdk-python\samples\basicPubSub\a987d73d1a-certificate.pem.crt -k C:\Users\bharath\Desktop\HP\Project\Code\AWS IoT\Python\aws-iot-device-sdk-python\samples\basicPubSub\a987d73d1a-private.pem.key

I know both these methods are wrong.
What is the correct procedure to give the arguments?

**Comment by liuszeng** [comment]
Hi @mvsnbharath ,

Thank you very much for your interest in AWS IoT Python SDK.

There is a space in your CA file name. You can either rename the file to a simpler name, e.g., rootCA.crt, or double quote the file path so that space is not counted when the sample is parsing the input parameters. See here:
http://serverfault.com/questions/591762/properly-escaping-a-path-with-spaces-in-cmd-shell

Hope the above helps.

Thanks,
Liusu

**Comment by mvsnbharath** [comment]
Yeah, it works absolutely fine mate.
Thanks a ton
I have one more issue, Is there a way AWS IoT respond to the incoming messages like
when I publish to the AWS IoT.
Client(On My PC) Publishes to AWS IoT: What is the Time
AWS IoT : Time xx:xx:xx.
I know MQTT is a pub/sub architecture but is there a possibility of the above.
If yes, are there any examples available ?(any language would do but more specifically python)

**Comment by lepirlouit** [comment]
you understand it right, about the publish subcribe. the only way to "respond" is to publish the answer on the same or another queue.

**Comment by liuszeng** [comment]
Hi @mvsnbharath ,

Glad that it is working for you.

As for the use case you mentioned, you can set up a IoT Policy, which triggers a lambda function that retrieve the time information for you and publish it to the dedicated topic.

Let's assume that your client will publish the following payload to request time to topic: `cloudEngine/request`:

    {
        "requestType": "Time"
    }

In the meantime, your client will subscribe to topic: `cloudEngine/response` to receive the time information.

In the cloud side, you will need to set up a lambda function, e.g., GetCurrentTime, that retrieves the current time and publishes it to topic `cloudEngine/response`.

Next, you will need to set up an AWS IoT rule that has the following query statement:

    SELECT * FROM 'cloudEngine/request'

and with the rule action to trigger the lambda function: GetCurrentTime that you just created. Enable the rule so it starts watching on incoming messages.

In this way, when your client starts up, subscribes to the response topic and publishes get time request to the request topic, that MQTT message will be captured by the AWS IoT rule and then forwarded to the lambda function as input. Your lambda function will be triggered. It will get the current time and publish it as another MQTT message back to the response topic. Your client will then be able to receive that time information as MQTT message.

For more information, you can check out the following documentation:
AWS IoT Rules Engine: http://docs.aws.amazon.com/iot/latest/developerguide/iot-rules.html
AWS Lambda: https://aws.amazon.com/blogs/aws/run-code-cloud/
AWS IoT Rule to trigger lambda functions: http://docs.aws.amazon.com/iot/latest/developerguide/lambda-rule.html
AWS SDK for Python (used in your lambda function): https://boto3.readthedocs.io/en/latest/reference/services/iot-data.html#IoTDataPlane.Client.publish

Thanks,
Liusu
