### ISSUE TITLE
Client disconnect after 24 hours without raising exception 

### ISSUE THREAD

**Issue by ghost** [aws/aws-iot-device-sdk-python#39]
When using the client with web socket, the mqtt client and shadow stop receiving updates from the service (broker or shadow updates).
I know that the web socket closes after 24 hours as listed in the aws-iot limitation.
However, the client is not raising any exception nor is it exposing any socket disconnect callback to handle this case.

**Comment by bxpan** [comment]
Hi Eyalbern,

Currently, the python sdk does not expose callback to client when it got disconnected, however, it should try to reconnect automatically by itself. Could you clarify if the problem you saw was that it does not reconnect automatically, and hence not able receive any further messages from server or publish any messages to server ? If so , do you have the logs for this period of time where it got disconnected but did not automatically attempted to reconnect ?

**Comment by eyalbern** [comment]
After 24 hours the client stop receiving updates from the service and not trying to reconnect, there are no warnings in the log (logger is set to DEBUG level).
however if the network disconnect before 24 hours the client is reconnecting when the network is back.and i get updates from the service.
As I understand its only when using web socket option.
Currently I have a timer that disconnects and reconnects every 23 hours, that way it continues to work nonstop.
I reach out to you for a more elegant solution to work with Aws-iot sdk.

**Comment by bxpan** [comment]
Hi Eyalbern,

This does not seem to be the expected behavior. The SDK should reconnect automatically after 24 hours. We will try to reproduce the issue and check further. 

Thanks.

**Comment by eyalbern** [comment]
Very easy to reproduce:
Just connect the AWSIoTShadowClient with the web socket option.
Wait 24 hours
And see that AWSIoTShadowClient is stopped getting updates when changing the shadow.
Also you will see that there where no exceptions.

**Comment by khyew** [comment]
I am seeing the same issue under the same conditions (watching for Shadow updates, using Websocket connection, >24hr uptime).

**Comment by thassman** [comment]
I see the same error, any update on this?
What could i implement as a workaround?

**Comment by thassman** [comment]
Thank you, i downgraded to sdk version 1.1.2 as disconnect did not work for me in 1.2

**Comment by liuszeng** [comment]
Addressed in v1.3.0.

**Comment by jp-embedded** [comment]
I am having this issue in v1.3.1

**Comment by rabingaire** [comment]
Did this issue got fixed? I am still disconnected after 24 hours.
