### ISSUE TITLE
self._shadowSubscribeCallbackTable[srcActionName]("REQUEST TIME OUT", "timeout", srcToken)

### ISSUE THREAD

**Issue by xelfer** [aws/aws-iot-device-sdk-python#4]
I'm using your SDK to send some sensor data to my IoT device shadow. It usually runs fine but the past day or two I've received this error when I re-attach my screen session:

```
payload: { "state" : { "reported": { "temp": "19.5", "humid": "55.3" } } }
payload: { "state" : { "reported": { "temp": "19.4", "humid": "55.2" } } }
payload: { "state" : { "reported": { "temp": "19.5", "humid": "55.3" } } }
payload: { "state" : { "reported": { "temp": "19.5", "humid": "55.3" } } }
Exception in thread Thread-6818:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/AWSIoTPythonSDK/core/shadow/deviceShadow.py", line 203, in _timerHandler
    self._shadowSubscribeCallbackTable[srcActionName]("REQUEST TIME OUT", "timeout", srcToken)
TypeError: 'str' object is not callable
```

Any ideas what might be going on here?

My full source is here: https://github.com/xelfer/nickshouse/blob/master/awstemp.py

Thanks,
xelfer

**Comment by liuszeng** [comment]
Hi @xelfer ,

Thank you very much for using AWS IoT Python SDK!

`AWSIoTMQTTShadowClient` provides APIs to interact with device shadow in AWS IoT by modifying shadow JSON document through MQTT Publish/Subscribe model. As a result, a callback can be registered to see if the shadow request has been accepted/rejected/timed out. The shadow callback, if need to be specified, should be in the form of `customCallback(payload, responseStatus, token)` (details available in [API doc](https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/generated/AWSIoTPythonSDK.core.shadow.deviceShadow.html#module-AWSIoTPythonSDK.core.shadow.deviceShadow))

In your source code [line33](https://github.com/xelfer/nickshouse/blob/master/awstemp.py#L33), you have specified the callback to be a string, which is not in forms of shadow callback and is not callable. If you do not want a callback for your shadow request, you can simply assign it with  `None`:

    myDeviceShadow.shadowUpdate(tempreading, None, 5)

Note that accepted/rejected callbacks are executed in separate threads other than the main application thread.

Hope that answers your question.

Thanks,
Liusu

**Comment by xelfer** [comment]
HI Liusu, thank you for the prompt response! 

I understand now and have changed my code. Thank you.
