### ISSUE TITLE
ThermostatSimulator device

### ISSUE THREAD

**Issue by escissorshand** [aws/aws-iot-device-sdk-python#41]
HI, i have problem running the ThermoStatSimulator.py. it provides an invalid syntax error on line 7. 

![image](https://cloud.githubusercontent.com/assets/24651418/25076072/5195b0de-2350-11e7-9ddb-bd8005f9a87f.png)

And on my serial monitor the setup monitor just hang on the following.

![image](https://cloud.githubusercontent.com/assets/24651418/25076138/d33a13e6-2350-11e7-81a5-c98ebd10047e.png)

However, i have shadow updates on the AWS IOT console. i believe the connection to the AWS IOT console is successful.

![image](https://cloud.githubusercontent.com/assets/24651418/25076163/fb89069a-2350-11e7-8bbb-0ece0fa900d7.png)

thanks in advance for your help.

**Comment by hedeshianaws** [comment]
Hello,

Did you mean to file this issue for the Arduino Yun SDK?

**Comment by escissorshand** [comment]
opps yes its for YUN SDK.

**Comment by liuszeng** [comment]
Migrated to: https://github.com/aws/aws-iot-device-sdk-arduino-yun/issues/44
