### ISSUE TITLE
createShadowHandlerWithName returns NoneType. 

### ISSUE THREAD

**Issue by Khalian** [aws/aws-iot-device-sdk-python#44]
```
 def defineIOTButtonShadow():
        print ("Begin shadow client init")
        myShadowClient = AWSIoTMQTTShadowClient("basicPubSub")
        myShadowClient.configureEndpoint(endpoint, 8883)
        myShadowClient.configureCredentials("root-CA.crt", "ArunavLaptop.private.key", "ArunavLaptop.cert.pem")
        myShadowClient.connect()
        time.sleep(1)
        myDeviceShadow = myShadowClient.createShadowHandlerWithName("Bot", True)
        time.sleep(1)
        print ("End shadow client init")
```

After this myDeviceShadow.shadowGet(cycleThroughDashBoardsCallback, 5) breaks because myDeviceShadow is NoneType.

**Comment by liuszeng** [comment]
Hi @Khalian ,

Thank you very much for your interest in AWS IoT Python SDK.

Can you elaborate more on the code base you shared here? Are you trying to initialize the client using the function `defineIOTButtonShadow`? When/Where is `myDeviceShadow.shadowGet(cycleThroughDashBoardsCallback, 5)` getting called?

Thanks,
Liusu

**Comment by liuszeng** [comment]
Hi @Khalian ,

We have not heard from you for a while. We are closing the issue for now. If you have any further questions, please feel free to re-open this issue or start a new thread.

Thanks,
Liusu
