### ISSUE TITLE
Library does not support Official Specs

### ISSUE THREAD

**Issue by heri16** [aws/aws-iot-device-sdk-python#47]
Cannot implement "Detecting a Thing is Connected" from the official documentation
[here](http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-data-flow.html) due to missing on_connect and on_reconnect callback.

**Comment by chaurah** [comment]
Hi @heri16,
    Those callbacks are being handled internally by the SDK at the moment. We are planning to expose those callbacks in a future release of the SDK. There is however a workaround that you can use to enable the callbacks. You can find details in [this](https://github.com/aws/aws-iot-device-sdk-python/issues/35) post. Please let us know if you have any further issues. Thank you for using AWS IoT.

Rahul

**Comment by liuszeng** [comment]
Addressed in release [v1.2.0](https://github.com/aws/aws-iot-device-sdk-python/releases/tag/v1.2.0).
