### ISSUE TITLE
Excepts if callback methods are part of class

### ISSUE THREAD

**Issue by LunkwillAndFook** [aws/aws-iot-device-sdk-python#48]
If callback methods are referenced from inside of a class (using self) the SDK excepts with the message Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(Thread-6, started daemon -1267731360)>>.

**Comment by hedeshianaws** [comment]
Hello,

Thank you for your interest in AWS IoT. Do you have a complete stack trace when this exception is thrown? Also, can you provide a small sample of how you were able to trigger the exception?

**Comment by liuszeng** [comment]
Hi @LunkwillAndFook ,

We have not heard from you for a while. We are closing the issue for now. If you still have any questions, please feel free to re-open the issue or start a new thread. Thank you very much for your interest in AWS IoT Device SDK!

Liusu
