### ISSUE TITLE
Waiting Infinitely at Connection type TLSv1.2 Mutual Authentication

### ISSUE THREAD

**Issue by Venkat2811** [aws/aws-iot-device-sdk-python#5]
Hi please find the log here http://pastebin.com/974DuwFF

I'm trying MQTT in basicPubSub.py

I'm using this certificate provided in AWS documentation as rootCA 
https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem

It is waiting infinitely at this point:
AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Connection type: TLSv1.2 Mutual Authentication

**Comment by liuszeng** [comment]
Hi @Venkat2811 ,

Thank you very much for using AWS IoT Python SDK!

Can you verify the integrity of your credentials through another MQTT client to see if you can connect to AWS IoT, e.g. [MQTT.fx](http://mqttfx.jfx4ee.org/)? It will be better if we can filter out credential configuration issue first. Also, have you made any modification to the sample? If so, is it possible for you share the code piece?

Thanks,
Liusu

**Comment by Venkat2811** [comment]
Hi @liuszeng 

Thank you very much for your quick response.

I'm using OS X and I tried the same with MQTT.fx .  But i had same problem.  It turned out to be that my open ssl is outdated.

I tried in Ubuntu VM and it is working fine.

Thanks,
Venkat.
