### ISSUE TITLE
Pub/Sub in 2 different Accounts.

### ISSUE THREAD

**Issue by mvsnbharath** [aws/aws-iot-device-sdk-python#53]
I was able to successfully implement the basicPubSub example but I see that in the example, you are publishing from the same AWS Account and Subscribing with  the same account.
How should I give my Policy statement if I would be Publishing messages from Account A and subscribing messages from Account B?
So, basically I want to know what is the change I need to perform to Pub/Sub across 2 different accounts.

Thanks
Bharath

**Comment by liuszeng** [comment]
Hi @mvsnbharath ,

Thank you very much for using AWS IoT Python SDK.

Currently, AWS IoT does not allow publish/subscribe from different AWS account for security reasons. Each account has its own MQTT topic space and cannot be shared across accounts.

Having said that, one thing you could do is to utilize the AWS IoT Rules Engine and AWS Lambda to apply resource based policy and enable cross account resource access. Let's say you have account A and account B. You want to be able to publish messages from account A and get it in account B. Here are some main ideas:
1. In account B, create a lambda function that republishes the received messages to "/fromAccountA/topic1". You can achieve this using boto3.
2. In account B, configure the resource based policy of that lambda function to allow account A to invoke it.
3. In account A, configure a rule in AWS IoT Rules Engine that routes messages received from "/toAccountB/topic1" to invoke a dedicated lambda, which is the lambda function in account B.
4. For the publisher, use credentials from account A to perform MQTT publish as is, publishing messages to "/toAccountB/topic1".
5. For the subscriber, use credentials from account B to perform MQTT subscribe as is, subscribing to "/fromAccountA/topic1".

In this case, whenever the publisher in account A publishes a message to the dedicated topic, it will trigger the lambda living in account B that republishes the same message to the dedicated topic in account B. Subscriber in account B therefore is able to receive it "as if" it gets it from the publishes happen in account A.

For more details, you can check out the following blog:
https://aws.amazon.com/blogs/iot/access-cross-account-resources-using-aws-iot-rules-engine/

Hope the above helps.

Thanks,
Liusu

**Comment by mvsnbharath** [comment]
Thank you so much 👍 
I got it working now.
