### ISSUE TITLE
Request and response strategy for AWS IOT MQTT?

### ISSUE THREAD

**Issue by mvsnbharath** [aws/aws-iot-device-sdk-python#56]
Does anyone have example or info on how to do request and response strategy / RPC with AWS IOT over MQTT? I would love to use AWS IOT system but I need to send a command, wait for a process to finish and get the results. It looks like I need a request and response strategy or RPC over MQTT.

**Comment by liuszeng** [comment]
Hi @mvsnbharath ,

Thank you very much for your interest in AWS IoT.

MQTT protocol itself is based on a Publish-Subscribe manner, which heavily relies on events/callbacks, not the traditional synchronous processing model. However, you can always build your own synchronous logic on top of asynchronous APIs by adding a time out blocking in the corresponding callback. You can take a look at the implementation of our IoT Java SDK as a reference:
https://github.com/aws/aws-iot-device-sdk-java/blob/master/aws-iot-device-sdk-java/src/main/java/com/amazonaws/services/iot/client/core/AwsIotCompletion.java

Are you using AWS IoT Device Shadow? Can you elaborate more on what you want to achieve on top of Pub/Sub here?

Thanks,
Liusu

**Comment by mkozjak** [comment]
@mvsnbharath: I wonder what you ended up with regarding this?
