### ISSUE TITLE
How to subscribe to multiple topics in aws iot?

### ISSUE THREAD

**Issue by mvsnbharath** [aws/aws-iot-device-sdk-python#59]
I have tried : 
`myAWSIoTMQTTClient.subscribe(['Topic1,'Topic2','Topic3'], 1, customCallback)`
`myAWSIoTMQTTClient.subscribe('Topic1,'Topic2','Topic3', 1, customCallback)`

None of them seem to work.  
I am able to successfully subscribe to 1 topic but not multiple topics.

**Comment by bxpan** [comment]
Hi mvsnbharath,

Currently, python SDK does not support subscribing multiple topics at the same time. 

Thanks.

**Comment by cnrmck** [comment]
Any chance this will be added? Would be very handy to have.

**Comment by sutiv** [comment]
Is it possible to do this now? I tried it in two separate scripts, but it works only if I use only one of them - parallel seems to be impossible

**Comment by jmklix** [comment]
No, you cannot subscribe to multiple topics at once. You can subscribe with a topic filter to effectively subscribe to multiple topics at the same time. For examples on how to do that look here: https://docs.aws.amazon.com/iot/latest/developerguide/topics.html
