### ISSUE TITLE
Publish request successful but the data not showing up in AWS server

### ISSUE THREAD

**Issue by rajibgupta** [aws/aws-iot-device-sdk-python#60]
I am publishing some message in a particular topic from a Raspberry pi and checking the data by subscribing to that topic in *AWS IOT web portal. Sometimes randomly in my python code running on the Rpi the publish request returns "TRUE" but data is not showing up in the subscribed window in AWS IOT web portal.
If I reboot the system it starts working normally. Then again the problem occurs randomly after some hours or days. 

note: I run the system 24*7

my publish code 

```
if myAWSIoTMQTTClient.publish("test1",line , 1):
                                        		print "Data Upload Ok"
                                        		uploaded = 1
                                        		del_t = round((time.time() - t),3)
                                        		print del_t,"ms taken to post to AWS" 
                                    		else:
                                        		print "Data Upload Failed.."
                                        		uploaded = 0
                                        		del_t = 0
                                        		print "not uploaded"
                                        		f.write(line)
```

The AWS IOT subscribe web portal I have mentioned is attached below.
![screenshot 19](https://user-images.githubusercontent.com/3149224/29684391-6c520b94-892f-11e7-85a7-858eee4d5a81.png)

Please help me out in finding the issue.
TIA

**Comment by liuszeng** [comment]
Hi @rajibgupta ,

Thank you very much for using AWS IoT Python SDK.

To further spot the issue, I have the following questions:
1. What type of authentication you are using to connect to AWS IoT from Python SDK? Are you using X.509 certificate or WebSocket IAM credentials?
2. Do you have any SDK log outputs captured when you were experiencing this issue?
3. To determine if the message gets lost on the publisher side or the subscriber side, I would suggest you to enable the cloudwatch log in your AWS IoT Console. You should be able to see a `PUBLISH` record in the cloudwatch log if the publish request made it to AWS IoT. Details of setting the log up can be found here: http://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html

Thanks,
Liusu

**Comment by rajibgupta** [comment]
Hi Liusu, 

Thanks for the quick response. 

1. I am using WebSocket IAM credential. 
2. I haven't captured but it was normal log output as if it is working fine from the publisher side. ( publish request succeeded with code ****). I will capture and post here at the earliest possible. 
3. I think it is enabled. I will check and get back soon. 

Thanks
Rajib

**Comment by rajibgupta** [comment]
Below attached is a sample log screenshot. This is not during the issue was happening but that time also log was similar.

![screenshot 20](https://user-images.githubusercontent.com/3149224/29686684-9302dcac-8937-11e7-806f-7bb6b9546d52.png)

**Comment by rajibgupta** [comment]
Can you please give a reference for setting up the cloudwatch log in AWS IOT console ? The link you gave earlier shows how to do it in AWS cli.

Thanks
Rajib

**Comment by rajibgupta** [comment]
Hey liusu,

I captured the log while the problem was happening and is attached below.

I would like to add some more information here. In my application 2 raspberry pis are connected to the same wifi for connecting to AWS and both them have same IAM credentials and certificates. They send two different data. The problem happens in either of them alternatively from time to time.Could this be the issue ? May be acknowledgement of one Rpi is being received the other ? 
![screenshot 21](https://user-images.githubusercontent.com/3149224/29726610-029425f6-89ee-11e7-93c2-09c744664a9a.png)

**Comment by liuszeng** [comment]
Hi @rajibgupta ,

Thank you very much for providing the information.

Regarding how to set up cloudwatch log in AWS IoT Console, you can check out the following screen shot:
![image](https://user-images.githubusercontent.com/14796906/29731263-a14e9cd6-8998-11e7-8aa2-d60008ddcdfc.png)
After enabling the cloudwatch log, you should be able to see log group for AWS IoT in CloudWatch console and see if the publish request made it to the server side.

Regarding the log output:
1. There is no log output indicating that the connection is lost, which means the publish request has been passed to the underneath paho for further delivery. We will have to verify the delivery using CloudWatch logs. Do you ever see any disconnect log output when you were experiencing the issue?
2. You mentioned that you have client on both of your RPis that connects to AWS IoT using the same IAM credentials. Can you confirm that you are using different client ids for those two clients? Within the same account, 2 connected clients with the same client id are not allowed and will result in disconnect.
3. With MQTT over WebSocket, you will have a maximum lifetime window of 24 hours for safety reason. After 24 hours, your MQTT over WebSocket connection will be closed by AWS IoT, which will trigger SDK reconnect.

Thanks,
Liusu

**Comment by rajibgupta** [comment]
Hi @liuszeng 

It turns out it was already enabled. See the below screenshot. This is what you are talking about?
![screenshot 24](https://user-images.githubusercontent.com/3149224/29738711-d35a21d6-8a48-11e7-8b94-317d7931e856.png)

1.Yes it gets frequently disconnected from time to time. At that point time it wasn't though.

2.Yes thanks for pointing out. This was a big mistake. I had given same client id for both of them. Now changed them.

3.I am aware of this. Even my system is programmed to reboot at every 24 hours. So no problem in this.

But even if the client ids were same the problem still seems weird and unsolved. Isn't it ?

**Comment by liuszeng** [comment]
Hi @rajibgupta ,

Thank you very much for providing the information.

From the CloudWatch console you should be able to access the AWS IoT log in `Logs` section and see all the events related to the client you've been using.

Since you mentioned that there were some frequent disconnects happened when you were experiencing the issue and you have assigned the same client id for two clients, they will be kicking each other off while SDK is trying to reconnect.

SDK publish will actively try to send the request to Paho for further delivery. Upon a disconnect event, SDK publish will then queue up the request until the recovery of the connection, in which case publish API returns a False. For disconnect event, SDK will not be able to detect it until the underneath Paho notifies the SDK with its event callback, which is triggered by any network failures or MQTT PINGRESP packet loss. Chances could be that your publish request gets queued up in Paho's outbound packet queue, waiting for the network I/O to flush it out, which, however, it was not successful sent due to some network failures. A recommendation would be to increase the keep-alive interval so that SDK sends out ping request more frequently if your connection activity is not high enough to detect disconnect event.

Are you still seeing the issue when you fix the duplicated client ids? What is your publish rate and your keep-alive interval configuration? For deeper details, I would also recommend you set up logging for the underneath Paho client. You can use its `on_log` callback mentioned here:
https://github.com/eclipse/paho.mqtt.python/blob/1.1/src/paho/mqtt/client.py#L384

Hope the above helps.

Thanks,
Liusu

**Comment by rajibgupta** [comment]
Hi liusu,

Thank you very much for a thorough analysis to my problem.

I am able to see the cloudwatch logs. Is the cloudwatch metric data same as log data ? Can you please explain a bit about the below screenshot. Note- I have around 5-6 clients connected to AWS IOT.
![screenshot 25](https://user-images.githubusercontent.com/3149224/29790783-7d5d647a-8c58-11e7-8ad9-19d9719cd470.png)

> A recommendation would be to increase the keep-alive interval so that SDK sends out ping request more frequently if your connection activity is not high enough to detect disconnect event
Did you mean to decrease the keep-alive interval ? How will it send out ping request more frequently if I increase it ?

My keep-alive configuration is 30 sec(The default one). My publish rate is once per minute.

**Comment by liuszeng** [comment]
Hi @rajibgupta ,

You can find my answers below:

>Is the cloudwatch metric data same as log data ? Can you please explain a bit about the below screenshot.

You want to click on `Logs`-> `AWSIotLogs` to get detailed log stream:
![29790783-7d5d647a-8c58-11e7-8ad9-19d9719cd470](https://user-images.githubusercontent.com/14796906/30132834-a54f64b0-9306-11e7-9fa5-c3322d06e7bc.png)
![screen shot 2017-09-06 at 1 25 29 pm](https://user-images.githubusercontent.com/14796906/30133012-1fd37d02-9307-11e7-9b9b-8b61e7842e24.png)

>Did you mean to decrease the keep-alive interval ?

Yes, I meant shorter keep-alive intervals and more frequent ping requests from the client side. Sorry for the confusion.

Thanks,
Liusu

**Comment by rajibgupta** [comment]
Thanks a lot liusu for the support.
After changing the client ids of all the nodes the problem seems to be solved.

**Comment by rajibgupta** [comment]
Hi @liuszeng 

The problem is there again. This time I captured the log at cloudwatch.
The problem is same. In my device(Rpi) with python SDK it publish event is successful but in AWS it's not getting published.

I have attached the cloudwatch log below.
![screenshot 27](https://user-images.githubusercontent.com/3149224/31011109-ba50a4d8-a52a-11e7-8b5a-75452eed6166.png)

What does it mean ?

**Comment by rajibgupta** [comment]
Any update on this please @liuszeng @vareddy ?

**Comment by dmateos** [comment]
I am having a similar issue where if i publish a shadow update from the callback of a mqtt sub the message says published but never shows up on the devices shadow.  If i call the same code instantly before the callback it is fine.

**Comment by ashwinpromethean** [comment]
On the same page then. Hopefully someone helps on this soon. Also if you are able to find the problem and solution please update here @dmateos  .
Thanks

**Comment by rajibgupta** [comment]
We are on the same page then. Hopefully someone helps on this soon. Also if you find the problem and it's solution please update here. @dmateos 

Thanks

**Comment by dmateos** [comment]
Is yours related to this?

https://github.com/aws/aws-iot-device-sdk-python/issues/82

**Comment by liuszeng** [comment]
Hi @rajibgupta ,

Sorry for the delay in responding. I am having some personal issues in the past months.

Are you still experiencing the issue? From the cloud watch log, it seems that there are some client error happened, but with not so much information for further investigation. Best chance for now is to set up the logging for the underneath paho using its `on_log` callback:
https://github.com/eclipse/paho.mqtt.python/blob/1.1/src/paho/mqtt/client.py#L384

To access the underneath paho (assuming you are using v1.1.2 from the logs you attached), you will have to take a look at the following links:
https://github.com/aws/aws-iot-device-sdk-python/blob/v1.1.2/AWSIoTPythonSDK/MQTTLib.py#L85
https://github.com/aws/aws-iot-device-sdk-python/blob/v1.1.2/AWSIoTPythonSDK/core/protocol/mqttCore.py#L155

Thanks,
Liusu

**Comment by liuszeng** [comment]
Hi @rajibgupta ,

We have not heard from your for a while. We are closing the issue for now. Please feel free to re-open it or create a new thread if you have any questions.

Thanks,
Liusu
