### ISSUE TITLE
Changes in AWS IOT python SDK latest release V1.2.0

### ISSUE THREAD

**Issue by rajibgupta** [aws/aws-iot-device-sdk-python#64]
Hi @liuszeng ,

Is there any documentation with all the changes in the recent version ? I have deployed the SDK in a couple of projects. I need to know if I really need to update all of them. 

Thanks

**Comment by chaurah** [comment]
Hi @rajibgupta,
    A full changelog is available here - https://github.com/aws/aws-iot-device-sdk-python/blob/master/CHANGELOG.rst
If you have any specific questions, please do let us now.

Rahul
