### ISSUE TITLE
Connectivity Info - implement __str__() or __repr__()

### ISSUE THREAD

**Issue by brettf** [aws/aws-iot-device-sdk-python#73]
It would be helpful for development if the entirety of the Discovery protocol implemented the `__str__()` and `__repr__()` methods, but if I have to pick one then the `ConnectivityInfo` class should be implemented first. Thank you.

**Comment by hedeshianaws** [comment]
Thank you for the feedback on the AWS IoT Python SDK. This looks like a good candidate for a pull request. I'd be happy to take a look if you were to submit one.

**Comment by hedeshianaws** [comment]
Closing due to non-response in 7 days. Please feel free to re-open if you have a pull request, or if you have any additional questions.
