### ISSUE TITLE
Filesystem error

### ISSUE THREAD

**Issue by hippie12** [aws/aws-iot-device-sdk-python#75]
![image](https://user-images.githubusercontent.com/23383531/31331902-8bb97a84-ace4-11e7-9856-a4bb5d1802c8.png)
I can't connect vie python to my files. Could you please explain how to set correct permissions in Windows 10?

**Comment by hedeshianaws** [comment]
You provided the same path "c:/cert" for the CA, private key, and device certificate. First, this path looks bogus. Second, you can't used the same cert for all 3. Please use a valid set of certificates, and make sure you are providing proper absolute paths.

**Comment by hippie12** [comment]
Oh yes i tried / and \ of course. Just to go sure there would be mo error like this. But i need to provide 3 different paths for each key ; cert and CA? Okay sounds logic. I try it and will see if i can connect like this.
Thanks for the help so far

**Comment by hippie12** [comment]
Anyways it didn't work.
So what is the difference if I use the Powershell and same certificates with the test script provided here in the tutorial? I can connect with PS script and there is no error, if script gives parameters like this:
python aws-iot-device-sdk-python\samples\basicPubSub\basicPubSub.py -e a1caxq12d8ru0y.iot.eu-central-1.amazonaws.com -r root-CA.crt -c Laptop-YD01NLZD.cert.pem -k Laptop-YD01NLZD.private.key

**Comment by hedeshianaws** [comment]
Since the CLI is working for you, what happens if you try this:

    C:> cd Users\svenm\aws-iot-device-sdk-python\samples\basicPubSub
    C:\Users\svenm\aws-iot-device-sdk-python\samples\basicPubSub>python
    Python 3.6.0 ...
    ...
    ...
    myMQTTClient.configureCredentials("root-CA.crt", "Laptop-YD01NLZD.private.key", "Laptop-YD01NLZD.cert.pem")
    ...
    ...
    myMQTTClient.connect()

**Comment by hedeshianaws** [comment]
Closing due to no updates in 7 days. Please feel free to re-open if you have any additional questions.
