### ISSUE TITLE
subscribeAsync's ackCallback is not called when done before connection is established

### ISSUE THREAD

**Issue by lightblu** [aws/aws-iot-device-sdk-python#79]
Firing subscribeAsync directly after the connectAsync call (which works in general) shows the ackCallback for the subscribe is not called then, because it is forgotten when it is an offline request.

This is, because in AWSIoTPythonSDK.core.protocol.mqtt_core.MqttCore.subscribe_async ignores the ack_callback if it goes to _handle_offline_request:

    def subscribe_async(self, topic, qos, ack_callback=None, message_callback=None):
        self._logger.info("Performing async subscribe...")
        if ClientStatus.STABLE != self._client_status.get_status():
            self._handle_offline_request(RequestTypes.SUBSCRIBE, (topic, qos, message_callback))
            return FixedEventMids.QUEUED_MID
        else:
            rc, mid = self._subscribe_async(topic, qos, ack_callback, message_callback)
            return mid      

Which then goes its way then through workers.py _handle_draining -> _handle_offline_subscribe:

    def _handle_offline_subscribe(self, request):
        topic, qos, message_callback = request.data
        self._subscription_manager.add_record(topic, qos, message_callback)
        self._internal_async_client.subscribe(topic, qos)
        self._logger.debug("Processed offline subscribe request")
        
        
 In contrast to the call to clients.InternalAsyncMqttClient.subscribe from MqttCore._subscribe_async 
 
    def _subscribe_async(self, topic, qos, ack_callback=None, message_callback=None):
        self._subscription_manager.add_record(topic, qos, message_callback)
        rc, mid = self._internal_async_client.subscribe(topic, qos, ack_callback)
        if MQTT_ERR_SUCCESS != rc:
            self._logger.error("Subscribe error: %d", rc)
            raise subscribeError(rc)
        return rc, mid
 
This problems is likely also present for the other calls with ackCallbacks in case of offline requests.

**Comment by hedeshianaws** [comment]
Thank you for using AWS IoT and reporting this issue. Got you loud and clear, let me take a look and get back to you.

**Comment by lightblu** [comment]
> This problems is likely also present for the other calls with ackCallbacks in case of offline requests.

Yes, it is at least the same for publishing. 

I publish directly in the ackCallback of the connectAsync call. Although the Client should be already connected it handles this as an offline request too, because the state change in the client seems to happen after dispatching the connection ack (which is maybe another minor issue).

Nevertheless, in case of offline publishes, the ackCallback gets ignored in the same way :(,
mqtt_core.MqttCore.ignores the ack_callback if it goes the handle_offline_request path:

    def publish_async(self, topic, payload, qos, retain=False, ack_callback=None):
        self._logger.info("Performing async publish...")
        if ClientStatus.STABLE != self._client_status.get_status():
            self._handle_offline_request(RequestTypes.PUBLISH, (topic, payload, qos, retain))
            return FixedEventMids.QUEUED_MID
        else:
            rc, mid = self._publish_async(topic, payload, qos, retain, ack_callback)
            return mid

**Comment by hedeshianaws** [comment]
@lightblu I apologize for the delay. I've heard back that is as designed, and should be considered a feature request. I've gone ahead and added it to the internal feature backlog for consideration. I can't promise a time-line at this point. Additionally, I've added a note to call out this limitation in the README for the next point release. I apologize for any inconvenience this has caused. Please feel free to open another issue if you have additional questions / comments.
