### ISSUE TITLE
Paho client Vs this SDK

### ISSUE THREAD

**Issue by Venkat2811** [aws/aws-iot-device-sdk-python#8]
Hi,

I'm curious to know, apart from Progressive reconnect back-off and offline publishing what is the advantage of using this client over native paho ?

Can I directly perform shadow operations using paho ?

**Comment by liuszeng** [comment]
Hi @Venkat2811 ,

Thank you very much for your interest in AWS IoT Python SDK!

The AWS IoT Python SDK is specifically developed for AWS IoT. It helps you to get quick access to AWS IoT MQTT functionality as well as device shadow functionality on top of it. It provides the following features up on top of Paho Python MQTT Client v1.1:
1. Auto-reconnect with progressive back off
2. Auto-resubscribe
3. Offline publish requests queuing with draining
4. Device shadow with token and version tracing
5. MQTT over WebSocket with IAM/SigV4

It is actively being maintained and developed as part of the AWS IoT Device SDK family and grows along with AWS IoT.

You can perform device shadow operations directly through Paho Python MQTT Client for sure. To do that, you will need to do MQTT subscribe and publish to reserved shadow topics. More details can be found [here](http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-data-flow.html). The SDK itself also serves as a reference that developers can check. Apart from the SDK, you can always built the development kit that is specifically tailored for your own application/device.

Hope that answers your question.

Thanks,
Liusu

**Comment by Venkat2811** [comment]
Hi @liuszeng 

Thank you very much for you quick response. Yes, I saw [this] (http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-data-flow.html) documentation and cross checked with you.

Is there any plan in AWS IoT platform to support other IoT protocols like CoAP ?

Thanks,
Venkat.

**Comment by hoihu** [comment]
CoAP would be interesting indeed...

**Comment by Venkat2811** [comment]
Yes..
