### ISSUE TITLE
New 1.2.0 async logic is more deadlock prone and could be documented/handled better

### ISSUE THREAD

**Issue by lightblu** [aws/aws-iot-device-sdk-python#81]
Switching to 1.2.0 made working code deadlock. We have an application, where multiple MQTT clients were initialized/run in multiple threads, doing some synchronization (also blocking) logic on top of that.

I pinpointed the issues to the locking code in workers.py around the threading.Condition self._cv used in both the EventProducer and EventConsumer object.
The deadlocks happening are self-made by our logic above (very simplified a message callback blocked waiting for another message, which now cannot ever be received because the dispatching of the first message holds the lock _cv forever), and so this is no bug,  still I would suggest to:

- Please point out such a significant and breaking change a lot more prominently, also in the changelog!
- It should get documented with big warnings, that blocking now has to be avoided in these callbacks, otherwise they will block all further message processing (which I see is kind of expected with this architecture, but wasn't the way it was before).
- The condition variable could use Lock with the timeout parameter (since Python 3.2), and then it would be possible to timeout in EventProducer._add_to_queue waiting for the cv and warn about a potential deadlock.
- The code in EventConsumer_dispatch and _dispatch_one should only do the queue.get while holding the lock, but dispatching an event should happen after the lock is released. That way, even when a callback blocks all further dispatching, at least the producer would not be starved. (Not sure how much this would help in the end, the nicest solution would be if dispatching happened from a thread pool and would allow some degree of parallel message processing we had before).

**Comment by hedeshianaws** [comment]
I apologize for the pain v1.2.0 has caused for you. In all fairness, 1.2.0 should have never been released as it never went though a design review. Unfortunately, we now have people using the v.1.2.0 specific features making a roll-back all but impossible. Rubbing salt in wound, the author is no longer available to address the issues. Please bear with me while I pick up the pieces.

**Comment by liuszeng** [comment]
Hi @lightblu ,

We have updated the documentation to call out the changes in v1.3.1. I also added an internal tracker for parallel message/callback processing. Sorry again for the inconvenience it has caused.

Thanks,
Liusu
