### ISSUE TITLE
ERROR:root:Errorname 'clientId' is not defined

### ISSUE THREAD

**Issue by flycast** [aws/aws-iot-device-sdk-python#88]
Am using [basicPubSub - CognitoSTS](https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/basicPubSub/basicPubSub_CognitoSTS.py).

I think the cognitoIdentyPool is the Federated Identity pool ID and NOT a user pool id.
I have figured out everything but the clientID. I am getting the following:

Code:
`    myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId, useWebsocket=True)
`

Error:
> ERROR:root:Errorname 'clientId' is not defined

I can't find any kind of client ID in the Federated Identity Pool settings except the client ID when using an Authentication provider. I created a user pool. In the user pool I created an app client. I then used the user pool ID and app client ID and added those values to the Federated Identities Pool > Authentication Providers > App Client ID. I then used the App client ID for the clientID value in the script. This did not work.

I also have a thing set up in IoT. I tried that thing's Name but that did not work either.

Part of the issue here is the docs/comments etc. do not specifically call out what the value is that it is looking or or which pool the value comes from.

What is the clientID value it is looking for?

By the way...I can see what look like new identities being created in the Federated Identities Pool identity browser from each time I try to connect.

**Comment by liuszeng** [comment]
Hi @flycast ,

Thank you very much for using AWS IoT Python SDK.

`clientId` is used to identify your MQTT connection. It is part of the MQTT protocol requirement and you can set it to any client id you want. In `basicPubSub_CognitoSTS.py`, it configures the default client id for you if you do not specify it via the command line input.

Is the error coming from the sample? Is it possible for you to share a code snippet that has this issue?

Thanks,
Liusu

**Comment by flycast** [comment]
Thank you for the fast response!
It does not matter what I set the clientID to.

```
from AWSIoTPythonSDK.MQTTLib import AWSIoTMQTTClient
import boto3
import argparse
import time
from decimal import *
import RPi.GPIO as GPIO
import time
import threading
import logging
import socket
import sys

try:
    clientID = 'testing'
    topic = 'cycles/' + clientID
    endpoint = 'XXXXXXXXXXXXXXXX.iot.us-east-1.amazonaws.com'
    rootCA = '/home/pi/certs/rootCA.crt'
    privateKey = '/home/pi/certs/XXXXXXXX-private.pem.key'
    certificate = '/home/pi/certs/XXXXXXXX-certificate.pem.crt'
    #Federated pool
    cognitoIdentityPoolID = 'us-east-1:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    
    
    # Cognito area
    host = endpoint
    rootCAPath = rootCA
    
    # Cognito auth
    print("Attempting to auth...")
    identityPoolID = cognitoIdentityPoolID
    region = host.split('.')[2]
    cognitoIdentityClient = boto3.client('cognito-identity', region_name=region)
    temporaryIdentityId = cognitoIdentityClient.get_id(IdentityPoolId=identityPoolID)
    identityID = temporaryIdentityId["IdentityId"]

    temporaryCredentials = cognitoIdentityClient.get_credentials_for_identity(IdentityId=identityID)
    AccessKeyId = temporaryCredentials["Credentials"]["AccessKeyId"]
    SecretKey = temporaryCredentials["Credentials"]["SecretKey"]
    SessionToken = temporaryCredentials["Credentials"]["SessionToken"]
    
    # Init AWSIoTMQTTClient
    myAWSIoTMQTTClient = AWSIoTMQTTClient(clientId, useWebsocket=True)
```

The last line is the issue.

**Comment by liuszeng** [comment]
Hi @flycast ,

Thanks for providing the information.

Shouldn't the last line be like:
```
myAWSIoTMQTTClient = AWSIoTMQTTClient(clientID, useWebsocket=True)
```

I saw you defined a `clientID` at the very beginning.

Can you correct that and try again?

Thanks,
Liusu

**Comment by flycast** [comment]
ZOWIE!
Thanks a bunch! That is the kind of issue that just kills me.
I know I can mark this closed but can I mark this thread embarrassing?
