### ISSUE TITLE
Using Custom Authorizer

### ISSUE THREAD

**Issue by guretno** [aws/aws-iot-device-sdk-python#90]
Hi,

Recently AWS release custom authorizer http://docs.aws.amazon.com/iot/latest/developerguide/iot-custom-authentication.html . When will this supported in python SDK? I saw that it already been supported in nodejs device sdk for IoT, and i've tested it and seems fine.

Basically what it need for MQTT with websocket (WSS) is the input param for custom-authorizer name, token name, and token signature (which then put into the header). And also when this mode is enabled, the sigV4 IAM credentials shuold not be sent. Thanks a lot.

**Comment by liuszeng** [comment]
Hi @guretno ,

Thank you very much for your interest in AWS IoT Device SDK for Python.

Unfortunately, the custom authorizer support is not included in the latest Python SDK release. Due to policy reasons, I cannot share an exact date of the support of this feature. Please stay tuned for future releases.

Thanks,
Liusu

**Comment by guretno** [comment]
Hi, just checking whether any feature update on this custom authorizeon AWS IoT Device SDk for Python? Thanks a lot

**Comment by liuszeng** [comment]
Hi @guretno ,

Thanks for the inquiry. The SDK is still pending on this feature. Please watch for future releases. Sorry for the inconvenience it has caused.

Thanks,
Liusu

**Comment by liuszeng** [comment]
Closing the issue as it has been captured in the team internal tracker.

**Comment by gnattwc** [comment]
Not sure if this is helpful but here is a stripped down example using paho.mqtt

[aws_iot_custom_auth_sample.py.txt](https://github.com/aws/aws-iot-device-sdk-python/files/2627149/aws_iot_custom_auth_sample.py.txt)

**Comment by mehtaparitosh** [comment]
Is this supported now? if yes, any code samples ?

**Comment by graebm** [comment]
Custom authorizers are supported in the [V2 IoT SDK](https://github.com/aws/aws-iot-device-sdk-python-v2).

There is not currently (July 2020) a code sample. To get custom auth working, you'd want to set a `websocket_handshake_transform` when calling [Connect()](https://awslabs.github.io/aws-crt-python/api/mqtt.html#awscrt.mqtt.Connection). You'd want your `websocket_handshake_transform` to look something like:

```
def my_websocket_handshake_transform(transform_args, **kwargs):
    transform_args.http_request.headers.add("x-amz-customauthorizer-name", "abc")
    transform_args.http_request.headers.add("x-amz-customauthorizer-signature", "xyz")
    transform_args.set_done()
```

Click here to read more about [WebsocketHandshakeTransformArgs](https://awslabs.github.io/aws-crt-python/api/mqtt.html#awscrt.mqtt.WebsocketHandshakeTransformArgs)
