### ISSUE TITLE
Make this code Pythonic

### ISSUE THREAD

**Issue by codeadict** [aws/aws-iot-device-sdk-python#93]
This code looks like written by a Java person, Camel cases in functions and variables and very unpythonic code style would be great to make it more friendly and compatible with the language standards. I volunteer for it if needed or is this code style something defined by Amazon?

**Comment by liuszeng** [comment]
Hi @codeadict ,

Thank you very much for pointing this out. We already have a open internal tracker planning to enforce this in future major releases. Please stay tuned.

Thanks,
Liusu

**Comment by codeadict** [comment]
Thanks!
