### ISSUE TITLE
Encode query params in websocket connection

### ISSUE THREAD

**Issue by pgrandinetti** [aws/aws-iot-device-sdk-python#95]
If I have a websocket endpoint similar to
```
url = "wss://eu.myiot.com/app?token=aufivu-adas=="
```
and the token is quite long (and contains both `-` and `=`, somewhere). So long that when I call (following your examples)

```
myAWSIoTMQTTClient.configureEndpoint(url, 443)
```
I get

```
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)
```
Can you suggest a solution?
Thanks a lot!

**Comment by liuszeng** [comment]
Hi @pgrandinetti ,

Thank you very much for using AWS IoT Python SDK.

Are you having this issue when connecting to AWS IoT? Can you specify which region and which auth. type you are using (with/without temporary auth. token)? If you are using MQTT over WebSocket to connect AWS IoT, the url signing part will be handled by SDK and you do not have to append any credential related query parameters by yourself.

Thanks,
Liusu

**Comment by pgrandinetti** [comment]
Hi, thanks for replying.
I am honestly slightly confused by how the python sdk works. If I type this simple lines in javascript it all works well
```
s = new WebSocket(<same-url-with-token-as-above>);
s.onmessage = function(e){
  console.log(e);
}
```
I can see the data printed in the browser dev console. And as you see this is not really a matter of region, auth.type, etc... It's simply an url with a token as query param. The fact that this is working so easily made me think there's some issue in the `myAWSIoTMQTTClient.configureEndpoint(url, 443)`, or more precisely in the token encoding.

I can tell you one more thing: if I do in python

```
url = "same-url-with-token-as-above>"
url.encode('idna')
```
I get the same exception as in the first message. One would say the token is really "too long" :)
Cheers

**Comment by liuszeng** [comment]
Hi @pgrandinetti ,

If you are trying to connect to AWS IoT, you endpoint should be similar in the following format:
```
<RANDOM_PREFIX>.iot.<REGION>.amazonaws.com
```
This would be the url you input using `configureEndpoint(...)`

Depending on which authentication type you are using, the SDK will generate the necessary signature internally, including query parameters like signature, token, etc. and use that for the final outbound request. More details can be found in the following examples:
https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/basicPubSub/basicPubSub.py
https://github.com/aws/aws-iot-device-sdk-python/blob/master/samples/basicPubSub/basicPubSub_CognitoSTS.py

Are you able to run the provided samples?

Thanks,
Liusu

**Comment by pgrandinetti** [comment]
Hi,
okay I see now, the connection works only to the `amazonaws.com` domain?
Cheers ;)

**Comment by liuszeng** [comment]
Hi @pgrandinetti ,

That is correct. Since the endpoint needs to be updated to accommodate with the authentication required by AWS IoT. If you would like to use the SDK to connect some custom MQTT broker, you will need to make some changes to the underneath MQTT client to disable the AWS specific signing process.

Please feel free to reopen the issue if you have any further questions.

Thanks,
Liusu
